### ISSUE TITLE
Allow db.table.all().update()

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#103]
The documentation says:

> You need to provide .where, .findBy, or .find conditions before calling .update. To ensure that the whole table won't be updated by accident, updating without where conditions will result in TypeScript and runtime errors.

This is a valid point, but sometimes user needs to actually update/delete all records, so there should be an escape hatch to do so.

I suggest to allow `db.table.all().update({ ... })` and `db.table.all().delete()`, same as Django does: https://docs.djangoproject.com/en/4.2/topics/db/queries/#deleting-objects

**Comment by bingtsingw** [comment]
It seems `db.table.where().update({ ... })` is the same as `db.table.all().update({ ... }) `

**Comment by IlyaSemenov** [comment]
Yes, but `.all()` clearly expresses user intention, and `.where()` without arguments sounds weird and should arguably be disallowed. Yet the former give typings error. 🤷

**Comment by capaj** [comment]
absolutely agree @IlyaSemenov, the API with `all()` makes a lot of sense.
Types for `where` should actually disallow `undefined` or `null` as input and that way in TS strict mode you can be sure to never accidentally delete/update whole table.

**Comment by romeerez** [comment]
I agree with the semantics as well.

Idea `all` was to negate the other kinds like `take`, for the case when some function returns a query with `take` or `find`, but you want to override it and return `all`. And `where` is here because `update` requires some conditions for safety. But, it should be possible to disallow the empty `where` and use the `all` instead.

**Comment by romeerez** [comment]
Done! `all().update(...)` and `all().delete(...)` are allowed now.
