### ISSUE TITLE
Add a `db.$query` function to perform queries using the existing transaction

### ISSUE THREAD

**Issue by romeerez** [romeerez/orchid-orm#133]
From the [discussion](https://github.com/romeerez/orchid-orm/discussions/131):

This won't use the transaction:
```
await db.$transaction(async () => {
  await db.$adapter.query(`some sql`)
})
```

Let's add a `$query` that will use it:
```
await db.$transaction(async () => {
  await db.$query(`some sql`)
})
```

**Comment by IlyaSemenov** [comment]
By the way, I would appreciate if you could somehow expose the current raw `pg` connection (client) for the active transaction.

The reason I'm asking is because I developed a set of hacks to run Objection/Knex transacting code inside a orchid/pqb transaction (for reusing legacy code). The only way I was able to pull the current connection was `db.user.internal.transactionStorage.getStore().client`, but:
1) The store is typed incorrectly as `AdapterBase` not `TransactionState`.
2) The code becomes coupled to a certain ORM table, because `transactionState` only lives in a local variable in [orchidORM()](https://github.com/romeerez/orchid-orm/blob/e28c0d0f7bcb27351c8b20ab778a235dee4241b2/packages/orm/src/orm.ts#L53).

These are minor nuances, so not a big deal if it's hard to achieve or leads to unwanted implications.

**Comment by romeerez** [comment]
The idea was to hide the transaction object completely so that transactions are fully managed by the ORM.

Currently, until `db.$query` is not implemented, you can use `db.user.internal.transactionStorage.getStore().adapter` as a workaround to get the object of the `AdapterBase` type that has the `query` method, why you don't like this type?

`TransactionState` is the object returned by `getStore()`, it contains the db `adapter`.

> The code becomes coupled to a certain ORM table

It's a single `transactionStore` for a whole ORM, and a separate `transactionState` is created for each transaction, I don't see any problems here

**Comment by IlyaSemenov** [comment]
> The idea was to hide the transaction object completely so that transactions are fully managed by the ORM.

Absolutely! This is all not needed when using Orchid only. However in a mixed environment, I want to pass the pg connection to legacy and/or third-party code.

> get the object of the AdapterBase type that has the query method, why you don't like this type?

Because I need the actual raw `pg` connection which I can then trick knex to use when it calls my fake [acquireConnection](https://github.com/knex/knex/blob/dab051b6da862c153b26df5b5e5f6c999a5994cf/lib/execution/runner.js#L305).

> TransactionState is the object returned by getStore(), it contains the db adapter.

Oh. Indeed it does now. I was testing with orchid-orm 0.4.14, the store was typed and structured differently. In 0.6.0, I see it has `adapter` which I can cast to `TransactionAdapter` to pull `client` in a type-safe way. Thanks.

> I don't see any problems here

The problem is that the orchid-knex adapter is dependent on **specific orchid db** (it uses hard-wired `db.user` which other dbs may not have). If there were something like `db.$transactionAdapter` that wouldn't be the case.

**Comment by romeerez** [comment]
Added `$query` and `$queryArrays` methods: [docs](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#query)

The transaction client is still not easy to obtain, not sure how to make and if it is worth making this clearer, for now you can define such a helper:

```ts
import { PoolClient } from 'pg';

const getTransactionClient = (q: Query): PoolClient => {
  return q.internal.transactionStorage.getStore()!.adapter.client as PoolClient;
}
```

`getStore()` will return `undefined` in case it's not called inside a transaction.

`adapter.client` has type `unknown` for the future when we'll have support for more than just `pg`.

**Comment by IlyaSemenov** [comment]
Thanks! That helper is just fine. This is an edge-case operation anyway.

**Comment by IlyaSemenov** [comment]
For the reference, the actual code would be:

```ts
await db.$transaction(async () => {
  const client = getTransactionClient(db.$queryBuilder)
})
```

**Comment by romeerez** [comment]
yes, exactly
