### ISSUE TITLE
[ask] `.parse()` changes where type

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#140]
This is my use case:

```
  testColumn: t.varchar().parse((v) => {
    switch (v) {
      case EnumXXX.A:
        return 'a';
      case EnumXXX.B:
        return 'b';
      case EnumXXX.C:
        return 'c';
      default:
        return 'd';
    }
  }),
```

I'm expecting `db.test.where({testColumn: EnumXXX.A })` to be worked, but it only accept the return type of `parse`

**Comment by IlyaSemenov** [comment]
How so you expect it to accept `EnumXXX.A`? 

The [documentation](https://orchid-orm.netlify.app/guide/common-column-methods.html#parse) says:

> The type of input is the type of column before .parse, the resulting type will replace the type of column.

The resulting type of a field becomes `'a' | 'b' | 'c' | 'd'`, so that's what is accepted as a field value.

If you want to advertise the parser to return a b c d or EnumXXX, either advertise that explicitly:

```ts
testColumn: t.varchar().parse((v): 'a' | 'b' | 'c' | 'd' | EnumXXX => {
```

or with a TS hint of a kind:

```ts
testColumn: t.varchar().parse(v => {
  switch (v) {
    case EnumXXX.A:
      return 'a'
    case EnumXXX.B:
      return 'b'
    case EnumXXX.C:
      return 'c'
    default:
      return 'd'
    // Hack: adverise EnumXXX as return type
    case 0 as any:
      return v as EnumXXX
  }
```

**Comment by romeerez** [comment]
Currently, this is how it works, a column has an input and output type, and the output type is used in `where`. I'll need to keep more types within a column to make it flexible enough for your use case.

**Comment by romeerez** [comment]
I published an update for this. Now the type for `where` is independent of the type which is set by `parse`, and your example should work as expected.
