### ISSUE TITLE
Run rake-db migrations programmatically with existing db connection

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#153]
I would like to run rake-db migrations programmatically, in a `beforeAll` unit test hook and using the current thread-local transaction.

This is what I would like to work:

```ts
beforeAll(async () => {
  await testTransaction.start(db)
  await rakeDb(..., ..., ["migrate"]).promise // just quick testing, I know this is wrong
})
```

The above code kinda works, but it opens a new database connection, so the tables are not rolled back on `testTransaction.close()`. I don't see a suitable low-level export in rake-db, moreover I can see that creating the connection is heavily coupled with running the migrations:

https://github.com/romeerez/orchid-orm/blob/cfef93300a6154bc82a7337cebf221f50d42d404/packages/rake-db/src/commands/migrateOrRollback.ts#L57-L69

I think this code could be extended with accepting a readily available `db.$adapter` instead of `AdapterOptions`? (Better yet, somehow refactored so that iterating adapters and running migrations through one of the adapters are separate).

---

I know that the documentation suggests to keep the test database in sync with the development one by providing the array of adapter options to `rakeDb` during migrations. However, I think the approach above also makes sense. It gives a small overhead during tests, but it reduces the pain of synchronizing, and it also makes sure the migrations are always in a good standing.

**Comment by romeerez** [comment]
That's requiring quite a lot of changes and will take some time.

But, why not use it as designed? So that `db migrate` will migrate both the dev and test dbs, `db rollback` will roll back both dbs, and when you run a test the test db is ready to be used.

The main idea and reason for test transactions is to make tests run "blazingly" fast, it's the fastest and simplest way to use a real database in tests, IMO.

With your approach, if you will have, let's say, a hundred test suites, and a hundred migrations, that means running 10k migrations each time when you run all tests, much more work for Postgres, now it will have not only the data but the db structure in memory. It's definitely going to be heavier and slower, but what are the gains?

**Comment by IlyaSemenov** [comment]
I actually do have 227 migrations with 48 tests in one of the projects which is more than 10k migrations per test run. That is with Knex/Objection where I didn't have `testTransaction` so the hooks were creating a new db, running migrations, and destroying the db after each test. At some point I replaced repetitive migrations with executing a single `schema.sql` (due to the strive for premature optimization, ha-ha) but the gains were very subtle. Overall, in my experience preparing the database(s) only takes a very small fraction of time in the whole test suite run.

As for the benefits, the primary benefit I see is that one does not have to deal with synchronization. Based on my experience, every now and then I f..k up with migrations (especially with non-trivial rollbacks involving data migrations) and have to perform manual maintenance on the local database. Imagine twice the efforts..with a chance of a different mistake... ugh. I tend to think about 'test environment' as of something transient which should require zero efforts.

Anyhow, I understand that it's requiring a lot of changes and is thus not worth it indeed. It's not a big deal. Similar to Knex, I went with using `schema.sql` with Orchid (generated in `afterMigrate`, executed in `beforeAll` with `db.$query`), that works well.

**Comment by romeerez** [comment]
> Imagine twice the efforts..with a chance of a different mistake

But why is it doubling the efforts?
If migration throws error, it's not persisted, both dbs aren't changed.
If migration passes, but you want to edit it, `db rollback` will rollback both dbs, then do you change, and `db migrate` will apply it to both dbs.
So it should act and feel like you're managing a single database. And indeed test database requires zero effort for maintaining. This approach worked fine for me on a work project. How it complicates things for you?

> A lot of changes and is thus not worth it indeed.

I don't mind doing it, though I'm fine not doing it as well. The change would slightly simplify `rakeDb` so it can accept a `db` instance that the user already has instead of connection options. And the fact you could have more control of it is a good thing in general.

**Comment by IlyaSemenov** [comment]
The problem I'm usually facing is that the down migration doesn't always fully and consistently rollback. If the up migration is destructuring, the down migration is supposed to put things back (e.g. re-create a table), and sometimes the developer fails to define that properly. They end up with a migration that has been supposedly rolled back yet the schema is broken and needs manual and sometimes non-trivial updates, which will be double work.
