### ISSUE TITLE
`create` type is not right after configure table relations

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#170]
I have a transaction table: 
``` typescript
export class TableTransaction extends BaseTable {
  readonly table = 'transaction';

  columns = this.setColumns((t) => ({
    ...t.baseColumns(),

    userId: t.varchar(),
    walletId: t.varchar(),
  }));

  relations = {
    user: this.belongsTo(() => TableUser, {
      required: true,
      references: ['id'],
      columns: ['userId'],
    }),

    wallet: this.belongsTo(() => TableWallet, {
      required: true,
      references: ['id'],
      columns: ['walletId'],
    }),
  };
}
```

The code below do not emit typescript errors which should be.
```typescript
await db.transaction.create({
  userId: 'userId',
  // walletId: '',
});
```

If I comment out one of any relations, type check returns.

**Comment by IlyaSemenov** [comment]
This is caused by `CreateRelationsData<T extends Query>` generic defined incorrectly:

https://github.com/romeerez/orchid-orm/blob/577903ee8fba02d58b1da8fbe0d7fcc3faec819e/packages/qb/pqb/src/queryMethods/create.ts#L63-L69

For the query above, it returns `{ userId: ... } | { user: ... } | { walletId: ... } | { wallet: ... }`.

Instead, it should be returning `({ userId: ... } | { user: ... }) & ({ walletId: ... } | { wallet: ... })`.

**Comment by romeerez** [comment]
Thanks @bingtsingw for finding it and @IlyaSemenov for digging into it. That's right it's about union/intersections.

After many hours of despairing attempts to fix it, now it should be alright!

https://github.com/romeerez/orchid-orm/blob/e19a5e3d4e131606a43e101633f112ed0d1ff05b/packages/qb/pqb/src/queryMethods/create.ts#L85-L91

By using such hacks it will now be checking types as expected in `({ userId: ... } | { user: ... }) & ({ walletId: ... } | { wallet: ... })`.
