### ISSUE TITLE
onConflict().ignore() doesn't alter return type to allow undefined

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#177]
An `.onConflict().ignore()` query will return `undefined` on conflict, however the typings don't reflect that:

```ts
const image_id = await db.image.get("id").create({ id: 1 }).onConflict("id").ignore()
// image_id is typed as number, yet it can easily be undefined
```

**Comment by romeerez** [comment]
This appears to be more complex to solve than expected ([SO answer regarding this](https://stackoverflow.com/a/42217872)), but interesting.

**Comment by romeerez** [comment]
Without getting deep into details, there are cases in which what is suggested in [that SO answer](https://stackoverflow.com/questions/34708509/how-to-use-returning-with-on-conflict-in-postgresql/42217872#42217872) cannot be implemented. Besides it's an abnormal query that can cause race conditions unless done super carefully.

So let the `ignore` indeed return undefined if not created.

> image_id is typed as a number, yet it can easily be undefined

I couldn't reproduce it, because `get` will throw on undefined. `getOptional` is returning a proper type.

Correct me if I'm missing something, but looks like no code updates are needed, only I should update docs to make this behavior clear. `onConflict().ignore()` may return nothing. In some cases, it may be a desired behavior. If it's not, there is `find().orCreate()`  that will always return data.

**Comment by IlyaSemenov** [comment]
> I couldn't reproduce it, because get will throw on undefined.

This makes sense, and I can't reproduce it now either. I was sure there was a typing error (I would open this without reason, I have to overcome the laziness every time lol), but now I'm not seeing it in the standalone reproduction script in the latest orchid. Sorry for the noise.

> Correct me if I'm missing something, but looks like no code updates are needed

Correct — I wasn't implying any (other than adding `| undefined` if there was a need — but apparently there is none). I'm not familiar with all the idiosyncrasies of `ON CONFLICT` so can't really advise on the specifics. I have no specific use case for pursuing these potential complex queries so I agree that it should be left as is for the time being.

**Comment by romeerez** [comment]
There was a bug: `table.create().onConflict().ignore()` didn't have `undefined` and now it will have.

And I changed `ignore` to add `undefined` in any case:

```ts
// can be undefined despite of `get`
const res: number | undefined = db.table.get('id').create(data).onConflict().ignore();
```

Updated [ignore](https://orchid-orm.netlify.app/guide/create-update-delete.html#ignore) docs to highlight this.
