### ISSUE TITLE
No-op update with empty input

### ISSUE THREAD

**Issue by romeerez** [romeerez/orchid-orm#185]
### Discussed in https://github.com/romeerez/orchid-orm/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **IlyaSemenov** September 15, 2023</sup>
I have this kind of boilerplate everywhere:

```ts
const { id, input } = schema.parse(ctx.args)
if (Object.keys(input).length) {
  await db.table.find(id).update(input)
}
```

I was thinking, what if ORM could do the check for me instead, and do a no-op update for an empty object?

Basically, that will mean that an empty update object will generate `select count(*)` instead of `update`, and generate `select *` instead of `update ... returning *`. Is that too magicky? Could it perhaps live in a dedicated method such as `.updateOrSelect`? (I don't like this particular name, just speculating.)

Just in case, currently an empty update simply generates invalid SQL:

```sql
UPDATE "table" SET  WHERE "table"."id" = $1
-- or
UPDATE "table" SET  WHERE "table"."id" = $1 RETURNING *
```</div>

**Comment by romeerez** [comment]
@IlyaSemenov idea: when called with an empty object, `update` will use the [none](https://orchid-orm.netlify.app/guide/query-methods.html#none) method internally, so the return type stays the same and the query won't throw.

**Comment by IlyaSemenov** [comment]
I am unsure about that. `db.find(1).none()` is supposed to crash with NotFoundError, isn't it? However, in my scenario above, `db.find(1).update({})` shouldn't crash — it should be a non-failing no-op.

I was thinking to have `db.find(1).update({})` always return 0, but that could potentially break workflows such as:

```ts
if (await db.where(condition).update(input)) {
  // objects found.
} else {
  // objects not found - somehow handle that.
  // will be false positively triggered for empty input.
}
```

Perhaps if that's documented that's not a big deal, but still that's kind of gotcha.

The safest approach would be to replace update with select (this will supposedly repeat the ORM update contract), but this sounds kind of odd.

That's why I opened a discussion and not an issue. I don't have a good solution to the problem, and not sure if it's worth solving at all. After all, that's not too much of a boilerplate in the first place. :)

**Comment by romeerez** [comment]
> The safest approach would be to replace update with select (this will supposedly repeat the ORM update contract), but this sounds kind of odd.

To me, it sounds like a good solution, (and I've already implemented it locally btw), why not?

```ts
db.table.where({ key: 'value' }).update({}) // SELECT count(*) FROM table WHERE key = 'value'

db.table.find(1).update({}) // SELECT count(*) FROM table WHERE id = 1

db.table.find(1).select('name').update({}) // SELECT name FROM table WHERE id = 1

db.table.find(1).get('id').update({}) // SELECT id FROM table WHERE id = 1
```

Following absolutely the same contract.

**Comment by romeerez** [comment]
Ready!

A little downside is that the `count` query is performed even if you don't really care about data returning. But I suppose this is not a big deal, since the empty update argument is an edge case that won't happen often.

**Comment by IlyaSemenov** [comment]
> why not?

Because `.update()` imposes a feeling that it's a relatively low-level wrapper around SQL `UPDATE` statement. The fact that it doesn't do any `UPDATE` at all in some cases will be unexpected by many if not most developers.

I am not saying this is exactly a bad thing, just giving arguments for "why not" :) it's probably a reasonable compromise in the end. 

Hopefully this replacement is safe to use in other edge cases (subqueries, weirdly locking transactions).
