### ISSUE TITLE
Abstract away snakeCase: true

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#197]
Disclaimer: there is no immediate need in this feature, I was justing reflecting on how things are organized and decided to raise this topic.

Currently, orchid has a few hardcoded options to manipulate names. In particular, this option:

```ts
createBaseTable({
  // Convert JS-side longNameField to DB-side long_name_field.
  // Uses some undocumented hard-coded implementation.
  snakeCase: true,
});
```

In one of my legacy projects I actually have the reverse need: camelize database fields, such as I need `person_category_id` from ORM to refer to `personCategoryId` in the database. Also, I imagine other scenarios where a developer might want to provide their own snake case conversion, such as when they're reusing it in different code layers and want to ensure consistency.

All and all, I believe this conversion should be abstracted away, and instead of `snakeCase: true` it should be something like `convertNames: snakeCase` where `snakeCase` is the default implementation that Orchid also exports.

Again, I am not saying that the current approach is wrong and/or that I actually need that new feature. It works and it is probably enough for most cases (and when it's not enough, there's always manual `t.name("...")`). I am just saying that it's the place which may benefit from a little flexibility and less hard-code.

**Comment by romeerez** [comment]
It's not worth implementing because, by JS naming conventions, we name all variables and properties in camelCase.

By default, ORM assumes that db also has camelCase, which saves CPU cycles on conversions. `snake_case` is a standard in dbs and ORM respects that and allows `snakeCase: true`. If you want `snake_case` on both sides that's also not a problem, simply name columns in `snake_case` and it won't transform names. If for some reason you need a column named differently, use `.name` column method.

> In one of my legacy projects I actually have the reverse need: camelize database fields, such as I need person_category_id from ORM to refer to personCategoryId in the database.

So to go against JS convention, against db convention, and to have columns named differently between the app and db. I'll never be able to implement all the useful features I can think of, because they are endless, and this one doesn't seem to be a good thing to support. If the columns can be renamed to camelCase on the app side - it better to do so, and if for some reason it's not an option, you'll have to add `name` to every column. In Drizzle ORM they always write both column names: for the app and for the db, and no problems.
