### ISSUE TITLE
Typescript Intelisense is very slow on my vscode

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#226]
Can we do something to optimize the DX?

**Comment by romeerez** [comment]
Yes, absolutely, and it's a priority for me. Can't promise it will be significantly better any time soon, hoping to gradually improve it during this year.

Last few weeks I have been working (and have been stuck for a while) on restructuring code for better column schemas exporting to zod, and the good news about that is that the compilation time of the query builder decreased by around 20%. (compilation time is slow because of the same reasons as intellisnse).

So it can be improved, but will take a lot of time and there are limits to how much can it be improved. Perhaps at some point will have to remove most TS-consuming features, or change interface for that.

**Comment by bingtsingw** [comment]
Thank you for your effort.

There is another thing that bothers me: the return type of `await db.query` is not inferred, I don't know if it will affect the performance

**Comment by romeerez** [comment]
Normally, when you hover the result in `const result = await db.query` it shows a cryptic (correctly inferred) type, I hope to improve it in the future to make it readable. On more complex queries when the editor suffers, it still infers the type correctly, but fails to display the type, it shows `any`. In fact, it's not `any`, if you access the wrong field TS will catch that. And when things get really frustrating, the editor highlights the whole query with red and gives up with "Type instantiation is too deep". Once I had an error like "Type is too long to serialize".

**Comment by bingtsingw** [comment]
Yes, the `result` type is correct but cryptic, that's exactly what I mean, happy to see you'd like to improve it

**Comment by romeerez** [comment]
I published an update ([PR](https://github.com/romeerez/orchid-orm/pull/228)) where removed redundant query methods, which weren't documented anyway so hopefully no one going to miss them.

This reduced type-checking time on a demo project from 7.3s to 6.6s - not bad for beginning.

**Comment by bingtsingw** [comment]
@romeerez Thank you for your excellent work!

**Comment by romeerez** [comment]
@bingtsingw I published another update with types optimizations, and now it should become noticeably faster: 20-25% type check time improvement on my demo project.

It would help if you could share some of your queries with table files where you experience the worst IntelliSense performance.

**Comment by bingtsingw** [comment]
Thank you @romeerez, I'll test the new version in recent days, and try to find some clues of slow query

**Comment by romeerez** [comment]
@bingtsingw, let me know if optimizations in the latest (orchid-orm 1.22.0) version do solve this issue. I expect Intellisense to become much better.

**Comment by bingtsingw** [comment]
Thank you romeerez, I'll test it in my next iteration.

**Comment by bingtsingw** [comment]
I upgraded `orchid-orm` to `1.23.0` in my codebase, it works perfect
