### ISSUE TITLE
RawSQL values method loses typings

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#239]
Calling RawSQL `.values()` method somehow breaks typings:

```ts
import { raw } from "orchid-orm"

// Works, no typing errors.
await db.user.where(raw({ raw: "id = $a", values: { a: 1 } }))

// Works, but shows type error:
// Argument of type '[RawSQL<QueryColumn<unknown, BaseOperators>, DefaultColumnTypes<ColumnSchemaConfig>>]'
// is not assignable to parameter of type 'WhereArgs<TableToDb<UserTable, EmptyObject>>'.
await db.user.where(raw({ raw: "id = $a" }).values({ a: 1 }))
```

* orchid 1.23.0

**Comment by romeerez** [comment]
Wouldn't you mind if I do the small breaking change quite soon? I thought to delay it, but it's so annoying that `where` can take different variants, and TS error is super confusing.

If I comment `TemplateLiteralArgs` type from `where` arg, TS errors tell why:

```
Type 'QueryColumn<unknown>' is not assignable to type 'QueryColumn<boolean | null>'.
```

This is because `where` does accept SQL that returns boolean, this helps:

```
db.user.where(raw<boolean>({ raw: 'id = $a' }).values({ a: 1 }))
```

In this case, it feels redundant, but `where` supports different cases, such as a callback returning a query with a value, and it's enforced to be a boolean (or null):

```ts
// gt returns boolean:
db.user.where((q) => q.posts.count().gt(5))

// forgetting gt results in TS error, count returns number
db.user.where((q) => q.posts.count())
```

**Comment by IlyaSemenov** [comment]
Sure, I enjoy working with Orchid and don't mind anything you do; I prefer fast turnaround to delays and workarounds due to backwards compatibility.

**Comment by romeerez** [comment]
@bingtsingw I hope this won't be a problem for you as well, I'm going to separate `where` that takes SQL:

```ts
// currently supported:
db.table.where`raw sql`
db.table.where(raw({ raw: 'raw sql' }))

// going to be `whereSql` instead:
db.table.whereSql`raw sql`
db.table.whereSql(raw({ raw: 'raw sql' }))
```

The same to be done for the `from` method, `having`, `order`, `find`, `where` variations such as `whereNot`.

I don't know if you use raw SQL extensively. Even if yes, this will be caught by TS so to go and replace.

**Comment by romeerez** [comment]
The problem with `raw` seems to be caused by an undiscovered magic of TS.

`values` method doesn't change type at all:

```ts
values<Self extends RawSQLBase>(this: Self, values: RawSQLValues): Self {
  this._values = values;
  return this;
}
```

It returns `this` - whatever it has before the dot.

`raw` function's type is meant to be `unknown` by default:
```ts
export function raw<T = unknown>(
  ...args: StaticSQLArgs
): RawSQL<QueryColumn<T>>
```

But this somehow works:
```ts
db.table.where(raw({ raw: '...' }))
```

Here TS sees that `raw` has `T = unknown`, and `where` is expecting a boolean and decides to set T to a boolean.

Let's keep this behavior, it's not critically bad, and I don't have ideas for how this could be changed.

**Comment by romeerez** [comment]
Published update for the comment above about `whereSql`.

Where still can take `raw`, and it still requires explicit boolean generic:
```ts
await db.user.where(raw<boolean>({ raw: "id = $a" }).values({ a: 1 }))
```

But `where`, `find`, `from`, `having` are no longer accepting SQL template with backticks, added `whereSql`, `fromSql` and so on to be used instead.

And now a TS error for `where` should become much clearer.
