### ISSUE TITLE
[ask] ormFactory.relation is never type

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#245]
<img width="434" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/4cfb2786-2c90-4944-9782-a5a75e7377f3">
<img width="352" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/a6c39d30-aac7-430d-930b-70820215dcb8">

`console.log(factory)` prints an object, but `console.log(df.city)` throws an error of `undefined is not an object (evaluating 'string._def')`

**Comment by romeerez** [comment]
There is a problem with test factories that it works only if you're using zod schema provider.
I'm not sure how to make it validation-lib agnostic and I've delayed this problem for later.

**Comment by romeerez** [comment]
Ready! Now test factories do not depend on zod and can be used without that.

I noticed that the original issue was probably caused by a typing bug not related to zod integration, but anyway now it should be working fine.

[Updated docs](https://orchid-orm.netlify.app/guide/test-factories.html).

Usability almost didn't change, there is a change for generating JSON data, added a section about that.
