### ISSUE TITLE
Not able to use zod validations in front-end. process is undefined error.

### ISSUE THREAD

**Issue by krishna-404** [romeerez/orchid-orm#273]
I am using a mono-repo have defined the tables, their types & zod validations in a common package, where the db is not initialised & only the the tables are defined.

orchid has a devDependency of `pg`. which uses `process.env` in their code. Which is throwing an error in frontend as `process is undefined`. Is there a work around for this? My frontend is Reactjs + Vite.

Thanks

**Comment by krishna-404** [comment]
I tried defining process at the global so the above issue was bypassed but ran into other issues like it is now searching for the `crypto` library.  `Buffer is not defined` error.

Is there someway we can use generated zod validations on the frontend? I dont want to re-write them, it leads to only errors in the long-run.

**Comment by romeerez** [comment]
I was a bit busy earlier, and planning to start figuring out new issues today and tomorrow.

As for this issue, I should make it clear in the docs that it is **not** suited for reusing zod validations in the frontend.
It's only suitable to use in the backend.

Because if you try to use the derived zod validation in your monorepo frontend, it means that your frontend will also pull the code of orchid orm and pg, increasing bundle size drastically.

So I'm afraid that for now, the only thing to do here is to define zod schemas manually separately from orchid-orm.

In the future, there could be a feature to generate those zod schemas separately, but that's for the future without ETA.

**Comment by krishna-404** [comment]
Totally get that. Maybe this is something we can work on when we adapt orchid for serverless environment, which would need proper modularisation & seperation of concerns... wheneever that is 🤞
