### ISSUE TITLE
why Text column type have min and max?

### ISSUE THREAD

**Issue by KMJ-007** [romeerez/orchid-orm#277]
```
Use t.text(min, max) type as a go-to for strings, other types are for special cases.

min and max number parameters define a validation of string length, they are required to ensure that the app won't accept empty or enormous values from user.
```

i got the point of min and max are used for validation in text but if i already know length of string or want to provide limited string length i will use `Varchar` not text,

both params(min, max) should be optional is what i am proposing, 

I am eager to understand your POV and the thought process behind making this decision!

Thanks

<img width="700" alt="image" src="https://github.com/romeerez/orchid-orm/assets/86996507/861e7229-2b90-4fb8-b2b9-cd6e114d779a">

**Comment by KMJ-007** [comment]
it's like saying it is unlimited but limited

**Comment by KMJ-007** [comment]
also

min and max are as single param, and they are making code little confusing, rather than that make them object so one can easily understand the property when sees schema

<img width="565" alt="image" src="https://github.com/romeerez/orchid-orm/assets/86996507/958d71a9-cf2c-4eba-9652-64e7cbe0738b">

**Comment by KMJ-007** [comment]
one workaround is defining baseTable and redefining text as 0 to infinity

```TS
export const BaseTable = createBaseTable({
	schemaConfig: zodSchemaConfig,
	snakeCase: true,
	columnTypes: (t) => ({
		...t,
		autoId: () => t.identity().primaryKey(),
		text: () => t.text(0, Infinity),
		createdAt: () => t.timestamps().createdAt.default("now()"),
		updatedAt: () => t.timestamps().updatedAt.default("now()"),
	}),
});

```

**Comment by romeerez** [comment]
Yes, I know it's very confusing and there is nothing like this in other ORMs.

This idea came to me when I was running tests using a mock data generator that was generating random text.
Unexpectedly, it was generating thousands chars long strings, and that made me think how damn many times I forgot to validate max length. It's a security whole. Just imagine if on your website someone's name is one million chars long, just for fun. It can break layout if you don't set CSS overflow, and it drastically increases page load time for anyone who visits, and increases server mem usage and loads network.

If you don't use a validation schema (there are integrations for zod or valibot), as I remember, the `text` won't accept min and max at all.

But if you configure it with zod or valibot, it's assumed that you going to use validations.

And if you're using validations, of course, you want text to be validated, so that users won't submit empty comments or extremely long comments.

> if i already know length of string or want to provide limited string length i will use Varchar not text,

Varchar doesn't check the min length, so users will still be able to submit empty names, comments, all kinds of content.

You may not know max length upfront, but set it to a reasonable 1000. Sometime later, you can change it to 2k, 10k, 500 - without a migration.

What if you use `varchar(100)`, but later requirements change and you want to change it to `varchar(50)`, but there already is content for more then 50? In the case of app-side validation, you can change it for the new content only, and the old content remains as it was.

> min and max are as single param, and they are making code little confusing, rather than that make them object so one can easily understand the property when sees schema

If you hover, it's clear from the function definition, and I believe it's simple to remember.

> one workaround is defining baseTable and redefining text as 0 to infinity

Yes, that works, you can also redefine `text` in there to accept `{ min, max }` as an object.

**Comment by bingtsingw** [comment]
I have a `createBaseTable` which re-define `text` function like this: `text: (min = 0, max = Infinity) => t.text(min, max),`

**Comment by IlyaSemenov** [comment]
I raised the similar concern the other day: #130. Some things have changed since that, but I still can't really comprehend the text primitives:

```ts
    varchar(limit?: number): VarCharColumn<DefaultSchemaConfig>;
    char(limit?: number): CharColumn<DefaultSchemaConfig>;
    text(min: number, max: number): TextColumn<DefaultSchemaConfig>;
    string(limit?: number): StringColumn$1<DefaultSchemaConfig>;
```

To me, they are inconsistent in arguments and somehow there are 4 of them (with 4 return types) while there are 3 types in the underlying database. Based on the documentation, both `string()` and `varchar()` map to Postgres `VARCHAR`, but how come their arguments are the same but the return type is different?

I also have to use the `min=0, max=Infinity` hack all the time. Good thing it's only one line in BaseTable, so it doesn't leak to the "user land" code.

**Comment by KMJ-007** [comment]
can we make these parameters optional?

what do you say?

**Comment by romeerez** [comment]
The idea was to force you to not forget setting text validations, but it brings more confusion than usefulness, so yes, I'll change that part sometime later.

Currently we have:
```ts
varchar(limit?: number): // varchar with no predefined limit
char(limit?: number): // just a db char type, quite useless
text(min: number, max: number): // db text type, requires min/max for validation on app side
string(limit?: number): // varchar with 255 by default
```

What's 100% clear, let's remove min and max from the text.
It's always possible to redefine it whatever you like in the `columnTypes`, but by default it won't take `min` and `max` at all, instead, it has methods `min` and `max` that you can use on occasion: `t.text().min(10).max(100)`.

`chat` is a useless type that was added because I aimed to cover 100% of db types.
But perhaps it would be better to remove it, and in an extremely rare case if it's needed it could be added in `columnTypes` by doing something like `t.type('char').as(t.varchar())`.

`string` is varchar with 255 by default. Why 255, not 200, not 300? I don't know :)
I thought it was nice to have so you don't have to think how many chars you need for first name, last name, post code, etc, just use `string` and 255 should be enough.
But, it's also easy to add in `columnTypes`, so I'm thinking of removing it, and if you want you can define it.

All the changes are breaking, so I will first mark `text(min, max)`, `string`, `char` as depreciated, and remove them in 3 months from now.

**Comment by romeerez** [comment]
I'm going to take care of this shortly,
- `text` - won't accept arguments
- `string` - I still like to have it with 255 by default - leaving it unchanged
- `varchar` - varchar must have a limit, otherwise there is no sense in it because it's equivalent to the text type - leaving it unchanged
- `char` - it shouldn't bother, leaving unchanged

So I'm going to change `text(min, max)` to simply `text()` and nothing more for this.

Only the `text` was confusing, and the rest seem to be alright overall.

**Comment by romeerez** [comment]
Published changes for this:
- `text` no longer accepts min and max, you can do `text().min(min).max(max)` if needed
- `varchar`'s limit becomes required, because without limit it's not different from `text`
- dropped `char`, as it's discouraged by Postgres

**Comment by mordechaim** [comment]
Typescript complains that `min` and `max` don't exist on the `text()` type

```
Property 'min' does not exist on type 'TextColumn<DefaultSchemaConfig>'
```

**Comment by romeerez** [comment]
That's right, it's not mentioned in this thread, `min` and `max` are enabled when you set up [validation](https://orchid-orm.netlify.app/guide/columns-validation-methods.html) with zod or valibot, so it's enabled additionally if needed.

**Comment by mordechaim** [comment]
Yeah missed this, thanks @romeerez
