### ISSUE TITLE
onConflict with reversed order of composite primary key fields gives type error

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#285]
If I use `onConflict` with composite primary key and put the key fields in reverse order, that gives type error. Not sure if it's worth fixing (I realise it could be caused by hacky infers and such), but I suppose it's worth documenting then.

```ts
import { createBaseTable, orchidORM } from "orchid-orm"

const BaseTable = createBaseTable()

class TestTable extends BaseTable {
  readonly table = "test"

  columns = this.setColumns(t => ({
    one: t.varchar(),
    two: t.varchar(),
    total: t.integer(),
  }), t => [
    t.primaryKey(["one", "two"]),
  ])
}

const db = orchidORM({}, {
  test: TestTable,
})

// No type error
await db.test.create({ two: "foo", one: "foo", total: 123 }).onConflict(["one", "two"]).merge()

// Error: Type '"one"' is not assignable to type '"two"'.ts(2322)
await db.test.create({ two: "foo", one: "foo", total: 123 }).onConflict(["two", "one"]).merge()
```

- orchid-orm 1.28.11
- typescript 5.3.3

**Comment by romeerez** [comment]
This is because the tuple type is preserved exactly as it was defined by you, it's simple to do both for me and TS.

Tuple manipulations in TS are possible, but cumbersome and expensive for TS to handle.

Imagine there are 10 primary keys, TS would have to construct a union of more than 1k combinations of those keys to use it as `onConflict` argument type. 1k doesn't sound huge in a computer world, but TS with tuple manipulations and large unions is definitely going to lag.
