### ISSUE TITLE
Chaining jsonSet allowed but doesn't work as expected

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#287]
As a developer, I sometimes need to update multiple JSON subfields. Chaining multiple `.jsonSet` in the update callback is seemingly allowed (there are no typing or runtime errors), but generates unexpected SQL. Only the last `jsonSet` is actually taken into account.

```ts
class PostTable extends BaseTable {
  readonly table = "post"

  columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    data: t.json<{ foo?: string, bar?: string }>(),
  }))
}

await db.post.find(1).update({
  data: q => q
    .jsonSet("data", ["foo"], "FOO")
    .jsonSet("data", ["bar"], "BAR"),
})
```

generates:

```sql
UPDATE "post" SET "data" = jsonb_set("post"."data", '{bar}', $1) WHERE "post"."id" = $2 ['"BAR"', 1]
```

What I would expect is the respective chained `jsonb_set(jsonb_set(...), ...)` call in SQL.

**Comment by romeerez** [comment]
Chaining them in SQL can't be the way, because you can technically chain `jsonSet`s for different columns.

I'm thinking about something like:

```ts
await db.post.find(1).update({
  data: q => q.jsonModify('data', (json) =>
    json
      .set(['path1'], value1)
      .set(['path2'], value2)
      .insert(['path2arr'], value3)
      .remove(['path2arr', index])
  )
```

**Comment by romeerez** [comment]
A better idea, this all can be chained with a minimal syntax:

```ts
await db.post.find(1).update({
  data: q => q.get('data')
    .jsonSet(['path1', value1])
    .jsonSet(['path2', value2])
    .jsonInsert(['path2arr', value])
    .jsonInsert(['path2arr', index])
});
```

But, a signature for `json*` has to change for this so it is a breaking change. Would you mind it?

**Comment by romeerez** [comment]
Published update, now you can use and chain `jsonSet`, `jsonInsert`, `jsonRemove` after `get` (or `ref` instead of `get` would be equivalent inside `update`).

```ts
await db.post.find(1).update({
  data: q => q.get('data')
    .jsonSet("foo", "FOO")
    .jsonSet("bar", "BAR"),
})
```

Renamed `jsonPathQuery` to `jsonPathQueryFirst` because it's using `jsonb_path_query_first` from Postgres, and maybe more similar methods will be added in the future.

Updated [docs](https://orchid-orm.netlify.app/guide/json.html), and [breaking changes](https://github.com/romeerez/orchid-orm/blob/main/BREAKING_CHANGES.md).
