### ISSUE TITLE
db.table().all().returnType is undefined in runtime

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#300]
`Query.returnType` is typed as a string, but it is undefined in runtime:

```ts
const t = db.table.all().returnType // typeof t is "all"
console.log(t) // undefined
```

I believe it won't hurt to set the runtime value and don't advertise false types. Orchid ORM probably doesn't use it other than for typings, but other tooling (such as I am developing) might do so in runtime, too.

**Comment by romeerez** [comment]
For runtime, all the changable table data is in `q` property:

```ts
const t = db.table.all().q.returnType // accessing q
console.log(t) // undefined
```

It's in `q` because it's a compact object that is cheaper to clone than a whole query, that's why all changable data goes in there.

But on type level, the whole query object has to be mapped on each change, and here it's cheaper to not have nested types.

I could move `returnType` type deeper so users can't see it, but TS service would become a little bit slower because of it, I don't think it's worth it.
