### ISSUE TITLE
can we maintain releases ?

### ISSUE THREAD

**Issue by KMJ-007** [romeerez/orchid-orm#308]
releases make it easier to see if there is a newer version of the package what's changed and what new feature has been introduced in this version so it helps in deciding whether to update to newer version or not

**Comment by KMJ-007** [comment]
i am aware about change logs being maintain at package level

**Comment by romeerez** [comment]
I don't know how to do that, because orchid-orm depends on pqb query builder, and most significant updates go to pqb. Github releases, as I can see from a brief search, only supports one package, and I can't choose only one, because changes in orchid-orm, and in pqb, and in migrations are important.

**Comment by bingtsingw** [comment]
There are [Release Page](https://github.com/romeerez/orchid-orm/releases), but I don't know why it not showing on the right of homepage

**Comment by romeerez** [comment]
Aha, I've found a button to attach that to the sidebar :)

All that noise of "Updated dependencies" is autogenerated by [changeset](https://github.com/changesets/changesets), and I don't know how to tune it for better.

**Comment by bingtsingw** [comment]
I think changeset is good enough for auto generated release notes.
By the way, the changeset md file can be edited manually.
