### ISSUE TITLE
Multi-tenant database?

### ISSUE THREAD

**Issue by krishna-404** [romeerez/orchid-orm#312]
How is Orchid in support multi-tenant databases? Say when using separate schema(db-level) / database for each user.

This seems to be lacking in most ORMs & I have a use case for it.

Thanks!

**Comment by romeerez** [comment]
It's lacking here as well.

It's a ton of work to do to support multi-schema properly, so this won't be ready in a foreseeable future.

**Comment by krishna-404** [comment]
Oh damn!

If you dont mind what would are the challenges, other than the migration stuff? Or is that where all the challenge is?

**Comment by romeerez** [comment]
Maybe not so much, depends on how you're going to do the multi-tenancy.

I had such project only once, and we were creating a separate db per tenant, and the app was opening a new connection for a request with connection url dependent on current tenant info. Currently, the ORM's db connection is configured once, and for multi-tenancy it would need some way to change connections on the fly.

The other multi-tenancy strategy is using different db schemas per tenant. From ORM's perspective, it could be handled in the same way as multiple dbs: to manage connections to the same db but with different schemas.

The thing that would indeed take much time to cover is using different db schemas in the same app, without multi-tenancy, I'm hoping to cover this some day, it's a lot because requires changes in a large amount of tests.

**Comment by krishna-404** [comment]
Hi! How about about multi-tenancy at the same db & schema level. Is there an easy way to achieve that? Thanks :)

**Comment by romeerez** [comment]
I'm willing to implement anything that can be useful, and to learn more in the process.
But I need requirements. And need to know that this will be used.

Multi-tenancy can be achieved in different ways. One of them is RLS, that's what I have in plans, and since Drizzle has it I can implement according to their docs.

The other way is to keep every tenant's data in their own db schema. This means creating a new db schema when registering a tenant, and running migrations for all the db schemas at once, and switching current schema on every request.

Another way is to do the same as for schema per tenant, but to use a database per tenant. As mentioned earlier, I had the multi-tenant request once, and this was the strategy. Nothing really was required from the db library for this, just switching connection settings on requests, and some additional code to run migrations for tenants.

**Comment by krishna-404** [comment]
RLS would be great. We can probably integrate that along with something we were discussing about `createdBy`, `updatedBy`, because RLS in the end is just extending an existing query.

Would love to contribute if you can point me in the right direction.

Thanks :)
