### ISSUE TITLE
Mutating query problem

### ISSUE THREAD

**Issue by KenjiGinjo** [romeerez/orchid-orm#329]
https://github.com/KenjiGinjo/orchid-reproduction/tree/K_329

**Comment by romeerez** [comment]
Repository instance (`dr.user` in your case) is a function, because it should support nested select:

```ts
// suppose a post has an author (in user table)
db.post({
  author: (q) => userRepo(q.author).something(),
})
```

When calling a repository method, it's no longer a function:

```ts
const res = userRepo.something() // res is not a function
```

That's why TS fails.

You can pass db.user to the dr.user and it will solve some of the problems:

```ts
let query = dr.user(db.user).where(...)
query = query.test1()
```

This is what I could do, published an update for this, and I'm not sure if I there are any more tricks to allow that assigning.

The following from your reproduction is allowed by TS only because table has just `name`. Once the table has a second column, it won't be allowed because query selecting all !== query selecting one column.

```ts
query = query.select('name')
```

But the `order` inside repo function should be ok, since it doesn't change the type.
