### ISSUE TITLE
External Use of db.table.select parameter types

### ISSUE THREAD

**Issue by minkoonim** [romeerez/orchid-orm#334]
I'm trying to make some sorta generic function to handle various tables,
```
const dbTables = {
table: Table
...
}

const db = orchidORM({ database, dbTables })

type TableName = keyof typeof dbTables
function useWrappedSelect<T extends TableName>(
  tableName: T,
  selectFields: Parameters<(typeof db[T])['select']>
) {
  //...
  return await db[tableName].select(...selectFields)....
}
```

but getting type errors, and also not getting type hint.
any suggestions on this?

**Comment by minkoonim** [comment]
pressed wrong shortcut, writing actual content at the moment.

**Comment by romeerez** [comment]
Instead of:

```ts
db.myTable.select('one', 'two', 'three')
```

You want to have:

```ts
useWrappedSelect('myTable', ['one', 'two', 'three'])
```

> any suggestions on this?

Sure, just use it how it was meant to be used :)

Why implementing a generic interface on top of it? You can see in `select` sources that the typings are quite crazy and your generic function would require a bunch of unmaintainable messy generic shenanigans.

`select` function is overridden 3 times:
- select('foo')
- select({ as: 'foo' })
- select('foo', { as: 'foo' })

And there are 3 different input types and output types for these cases, you'd need to collect args into a generic and do a ternary to find out the corresponding output type.

Also, I struggled a lot with `select` typings to decrease laptop heating when TS analyzes them, so adding on top is dangerous.

**Comment by minkoonim** [comment]
makes sense 
thanks man
