### ISSUE TITLE
 If I have a table named 'order' and then 

### ISSUE THREAD

**Issue by KenjiGinjo** [romeerez/orchid-orm#337]
```
// If I have a table named 'order' and then 
await db.table.where(..).order({updateAt: 'DESC'})
// "SELECT \"order\".\"updateAt\" FROM \"order\""
```

**Comment by KenjiGinjo** [comment]
for now I can use

```
await db.table.where(..).orderSql`update_at desc` // this is ok
```

**Comment by romeerez** [comment]
Kenji means he has one table named no matter how, and a related table "order".
Such as user has an order.

It's funny how I couldn't foresee this coming, lol.

[relation queries](https://orchid-orm.netlify.app/guide/relation-queries.html), first example:
```ts
const author = await db.book.author(book);
```

The same with user and order:
```ts
const order = await db.user.order(book);
```

Quite simple and understandable solution would be for ORM to append `Query` into this case:

```ts
const author = await db.book.authorQuery(book)
const order = await db.user.orderQuery(user)
```

`QueryFor` may read better:

```ts
const author = await db.book.authorQueryFor(book)
const order = await db.user.orderQueryFor(user)
```

Or maybe prepent, this is a little bit heavier for TS because need to use `Capitalize` type util:

```ts
const author = await db.book.queryAuthorFor(book)
const order = await db.user.queryOrderFor(user)
```

Another option that possible may even decrease load on TS checker, I'll check if this will make a difference:

```ts
// or just `related`
const order = await db.user.queryRelated('order', user)
```

**Comment by romeerez** [comment]
Solved!

Introduced `queryRelated` and `chain` methods to avoid naming conflicts.

You original code example:

```ts
await db.table.where(..).order({updateAt: 'DESC'})
```

Now should work as expected.

If you'd like to load an order for the table record:

```ts
const tableRecord = await db.table.find(id)
const relatedOrder = await db.table.queryRelated('order', tableRecord)
```

And if you'd like to "chain" - to load orders based on a table query:

```ts
const orders = await db.table.where(...someConditions).chain('order')
```
