### ISSUE TITLE
Allow empty where with soft delete

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#347]
I have a function that queries a table and optionally pass filters:

```ts
interface Filters {
    user?: number
}

async function list(filters?: Filters) {
    return await db.myTable.where({
        userId: filters?.user
    }).select()
}
```

It works all well, until I added a softDelete to `myTable`. All of a sudden the query started failing when the optional filters weren't passed. After debugging I found that the soft delete with empty where created the following invalid SQL:

```sql
WHERE () AND ("my_table"."deletedAt" IS NULL)
```

My current workaround is calling `where()` conditionally (reassigning a `query` variable) instead of always calling and relying on `undefined` to not filter when not present.

**Comment by romeerez** [comment]
I published a fix, it should now be working as expected.

Though, it seems dangerous to allow empty wheres like that, because the code looks like it deletes only users filtered by conditions, but if any mistake is made it can delete all the users entirely, luckily you have soft delete and can recover, but the same is possible without soft delete.

How do you think, perhaps it's better to keep that behavior of throwing error, just making the error more explicit?

**Comment by mordechaim** [comment]
Thanks 👍 

> it seems dangerous to allow empty wheres like that, because the code looks like it deletes only users filtered by conditions

I'm trying to _select_, not delete. Optionally, I allow passing filters to the select.

I'm used to this paradigm from Prisma, where `undefined` is treated as not provided. It makes constructing queries more ergonomic IMHO.

**Comment by romeerez** [comment]
For some reason I thought it's about delete, but select should be also fixed by the same fix.

Sure, it's very convenient and Orchid ORM also strips undefineds from where, create, update, and whenever they can be.
