### ISSUE TITLE
Array of strings parsed incorrectly if element contains double quote "

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#371]
With a column typed as `t.array(t.text())` and having `text[]` in the database, text elements with a double quote (") break result parser:

```ts
await db.user.insert({ data: ["a\"1"] })
// INSERT INTO "user"("data") VALUES ($1) ['{"a\"1"}']

console.log(await db.user.get("data"))
// [ 'a\\"1', 'a\\"1"' ]
```

- orchid-orm 1.35.0

<details>
<summary>Full reproduction</summary>

```ts
import process from "node:process"

import { createBaseTable, orchidORM, testTransaction } from "orchid-orm"

const BaseTable = createBaseTable()

class UserTable extends BaseTable {
  override readonly table = "user"

  override columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    data: t.array(t.text()),
  }))
}

const db = orchidORM(
  { databaseURL: process.env.DATABASE_URL, log: true },
  {
    user: UserTable,
  },
)

await testTransaction.start(db)

await db.$query`
create table "user" (
  id serial primary key,
  data text[]
);`

await db.user.insert({ data: ["a\"1"] })
console.log(await db.user.get("data"))

await testTransaction.close(db)
```
</details>

**Comment by romeerez** [comment]
Its a Postgres fault.

When you load regular columns/rows, in the underlying protocol pg sends a header that defines all column names and types, and then sends rows. It's basically a CSV with a header.

When you load JSON values, it's parsed as a regular JSON.

But the array type is super annoying, it's not trivial to parse at all. That's why I postponed array parsing.

I even thought that correctly parsing arrays (that can contain any data and can be nested) is a doomed idea, and instead it's easier and safer to convert arrays to json at a db level when loading data. But then, what the point of storing arrays, if it could be json and wouldn't require transforming when loading.

I'm still postponing this for now, and going to look for possible solutions later.

Maybe, it's enough to support a few common array cases (strings, numbers, booleans) and highlight in the docs that for more complex types please use JSON instead, or normalize the data by keeping it in additional tables.

**Comment by romeerez** [comment]
Published a fix: changed array parsing to how it's done in [postgres-array](https://github.com/bendrucker/postgres-array/tree/master) library and it became better.
