### ISSUE TITLE
Feature for not selecting specific fields in query method select

### ISSUE THREAD

**Issue by Pras2214** [romeerez/orchid-orm#393]
Is there an option to unselect/ not select any specific fields in the select query?

e.g.:
Want all fields except name

Prisma and other ORMs have this feature, so if there is any similar feature available please guide me to it in the docs, otherwise I would be more than happy to contribute.

```javascript 
const applications = prisma.application.findMany({
        // Returns all except username
        include: {
            username:false
        },
    })
```

**Comment by romeerez** [comment]
Unselecting like that isn't planned because it feels like a bad practice to me.

New columns are added over time, it is expected to happen, so it is expected that your code in such case will load more data that it doesn't need.

Typically, you either select all (default) because it's simpler, or you select strictly what is needed.

There is one related idea, though. It is delayed for the future because it requires quite a lot of changes (easy to implement, but big impact on tests), and it wasn't requested by community.

It is marking a column as `hidden`: useful for the password column, you never want password to be selected except just a single place where you verify password. By default, hidden fields won't be selected, can be selected explicitly. `hidden` may be not the best name, perhaps `myColumn: t.text().select(false)` will be more intuitive.

**Comment by KMJ-007** [comment]
i think the request is valid and i also understand your pov.

like i have 20 columns and only 5 columns are not needed then in that case i would need to define 15 columns, good practice but bad dx

**Comment by IlyaSemenov** [comment]
I am actually with @KMJ-007 on this. The current way of things which allows (and in a way, endorses) `db.table.find()` without explicit `.select()` is similarly a bad practice on its own. Not once I rejected this kind of code on code reviews when developers carelessly selected all fields and not only needed, and most probably I've missed some of those too.

Adding `db.table.find().exclude()` is not making this any worse. It suffers from the exact same "new fields will be added and the code will behave differently" problem as plain `db.table.find()`, so why limiting the former and keeping the latter?

---

Solving this for good, I'd actually consider disallowing select-less queries. In my thinking, a resolving query should always end with select, insert, update, or aggregate. If a user wants all fields, they better explicitly type `.select("*")` admitting shooting in their foot. Then, `select("*").exclude("password")` is not less valid.

Of course, this will break lots of existing code so it's a controversial decision.

**Comment by IlyaSemenov** [comment]
@KMJ-007 If this is an one-off piece of code, you can use something like this:

```ts
await db.table.select(...db.table.columns.filter(col => !["createdAt", "updatedAt"].includes(col)))
```

**Comment by romeerez** [comment]
I still think it's better to not add the excluding select feature.

> like i have 20 columns and only 5 columns are not needed

If the table already has 20 columns, it's almost guaranteed to have 30 a few months later.
You exclude 5, and load 10 redundant a few months later.
Other developer will see that you're excluding 5, loading 25, and won't know which ones are redundant.

> selecting all is similarly a bad practice on its own
> when developers carelessly selected all fields and not only needed

This is what developers do most of the time. If the select was required, devs would always write `select('*')`, and ORM's goal is to help devs, so it happens automatically.

Selecting all is arguably a bad practice, depends on how much do you care.
If the query is running internally and result isn't exposed to clients, selecting more than needed is cheap and simple, doesn't harm, less code.

If the query result is exposed to clients, it is still fine in most cases. We can look at the network tab on any popular website - most likely it sends much more data than is actually needed, and still it works, may be successful, reducing JSON size may be a premature optimization that won't be worth time.

If you use graphql, it spends precious CPU resources to strip not requested fields anyway.

So if it's not important in your case, selecting all is fine.

But when it is important, list the exact required columns.

Other question is to mark columns in a table to not be selected by default, it should be done for passwords and other sensitive data. Excluding passwords on query level isn't much useful, because it's easy to forget to exclude it.

> Solving this for good, I'd actually consider disallowing select-less queries.

It's possible to support as opt-in, if you really would like to have it.

**Comment by romeerez** [comment]
I published `select(false)` for columns, you can mark sensitive columns with it and then they can only be selected explicitly: [exclude from select](https://orchid-orm.netlify.app/guide/common-column-methods.html#exclude-from-select).

You can define select sets in [repositories](https://orchid-orm.netlify.app/guide/repo.html#repository).

**Comment by IlyaSemenov** [comment]
> It's possible to support as opt-in, if you really would like to have it.

It would be nice to have (if it were there I'd absolutely give it a try and see how it affected DX), but by all means it's not critical.
