### ISSUE TITLE
Array of JSON objects returning empty data in Orchid ORM

### ISSUE THREAD

**Issue by JAYBORICHA07** [romeerez/orchid-orm#415]
When defining a column as an array of JSON objects using:

current schema:
``` ts
postsData: t.array(t.json(z.object({name:z.string()})).nullable()).nullable() 
```
when i try to perform simple find query it returns an empty array, even though data exists in the database.

column  type is jsonb in database and data is present and easily queried using sql.

Expected Behavior : 
The query should return the array of JSON objects, similar to how it works when defining a single JSON object:

**Comment by romeerez** [comment]
Apparently, it's not currently supported, JSON already supports array, can't you use JSON array instead of array of JSONs?

```ts
postsData: t.json(z.object({name:z.string()}).array()).nullable()
```

Also, AFAIK it's not supported on a database level to have nulls in db array.

**Comment by romeerez** [comment]
I published a fix, now it works properly on my side, but I think there is something else in your case.

For me it wasn't properly working because JSON string wasn't parsed, so I was receiving an array of strings, and published a fix so those strings now will be parsed with JSON.parse.

But in your case, you're saying the array is empty, so there is something else.

Are you sure it's `jsonb[]` type in db?

If you have `jsonb` without `[]` in db, you should use JSON array instead of array of JSONs.

```ts
// from your code, array of JSONs
postsData: t.array(t.json(z.object({name:z.string()})).nullable()).nullable() 

// JSON array
postsData: t.json(z.object({name:z.string()})).nullable().array()).nullable(),
```
