### ISSUE TITLE
Property 'trim' not recognized on string columns in Orchid ORM v1.31.7

### ISSUE THREAD

**Issue by KMJ-007** [romeerez/orchid-orm#417]
When defining string columns in Orchid ORM tables, TypeScript is reporting an error for the `trim()` method:

```typescript
Property 'trim' does not exist on type 'ColumnTypeBase<ColumnTypeSchemaArg, unknown, any, any, unknown, unknown, any, unknown, any, ColumnDataBase>'.ts(2339)
```

This error occurs on lines like:

```typescript
title: t.string().trim().nullable(),
```

Environment:
- Orchid ORM version: 1.31.7 (as specified in package.json)
- TypeScript version: 5.4.5

Expected behavior:
The `trim()` method should be recognized as a valid method on string columns.

Actual behavior:
TypeScript reports an error, suggesting that `trim()` is not a valid method on the column type.

Steps to reproduce:
1. Create a table definition extending `BaseTable`
2. Define a string column using `t.string().trim()`
3. Observe the TypeScript error

**Comment by KMJ-007** [comment]
any updates on this?

i have tried to downgrade the orchid but don't know still i am facing the issue

**Comment by romeerez** [comment]
I'm busy on work days so can't fix things, and as I can't fix things there is not much sense investigating and responding.

Looks like this is a bit confusing and may be unexpected, but that's not a bug, but works as intended.

[trim](https://orchid-orm.netlify.app/guide/columns-validation-methods.html#text-columns) is a "validation" method, even though it's not validating, but it is meant to be a part of validation.

OrchidORM intentionally does **not** perform any validations, including `trim`, when updating or saving records, because I think it's better to be done in the controller, and after it there is no sense to validate and transform values during updates and creates.

When you install zod or valibot integration as described in the [validation](https://orchid-orm.netlify.app/guide/columns-validation-methods.html) section, `trim` and all the rest validation methods become available, then you can use `SomeTable.inputSchema()` to validate incoming data, and strings will be trimmed by zod or valibot during that phase.
