### ISSUE TITLE
[bug] some repo query is not working in subquery

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#423]
https://github.com/bingtsingw/orchid-reproduction

**Comment by bingtsingw** [comment]
Seems it's only not working in this `parentId` pattern, which joins the same table has a table name collision.

**Comment by bingtsingw** [comment]
I just found that `order()` field has collisions too.
```
await commentRepo
  .find(comment.id)
  .selectForList()
  .select({ subcomments: (q) => q.subcomments.select('id', 'createdAt', 'rootId').order({ createdAt: 'ASC' })
  .order({createdAt: 'DESC'})
```

The order is totally chaotic

**Comment by romeerez** [comment]
Ready, fixed!

One thing in your repro, change `.where({ id: comment.id })` to `.find(comment.id)` because the test is expecting an object.

It was because of a collision: the inner query's table is `comment`, the outer table is also `comment`, sub query tries to alias the inner table as `comment2`, but `makeHelper` was discarding it. And now I fixed `makeHelper` to respect the alias.
