### ISSUE TITLE
Error when using group() with nested relations

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#430]
When trying to use `group()` with nested relations through `chain()`, the following error occurs:
```
error: could not identify an equality operator for type json
code: "42883"
```

### Reproduction Steps
1. Set up related tables (user, region, location, userCheckIn)
2. Create records with relationships between them
3. Attempt to query with grouped nested relations

### Example
```typescript
const result = await db.userCheckIn
  .select("locationId", {
    locationRegion: (q) => q.location.chain("region"),
    checkInCount: (q) => q.count(),
  })
  .group("locationId", "locationRegion.r")
  .where({ userId });
```

Here's the minimum reproducible example to save time: https://github.com/matthewmorek/orchidorm-group-issue

I've tried to work around it using different ways to query for relations (joins, chaining, etc), but nothing works. Any ideas on how to work around it would be appreciated!

**Comment by romeerez** [comment]
Apologies for not responding earlier, I wish I could respond with smaller delays, but it's not always possible.

So here the problem is that GROUP BY doesn't want to group by json values. I don't think it's a bug or a missing feature that is worth implementing.

`locationRegion.r` - the `r` part is an implementation detail and it's intentionally not exposed. 

#### select a plain value instead of full object

This is only if you want to select a single value from the regiion:

```ts
const result = await db.userCheckIn
  .select("locationId", {
    locationRegionName: (q) => q.location.chain("region").get("name"), // <-- get('name') selects just the name
    checkInCount: (q) => q.count(),
  })
  .group("locationId", "locationRegionName") // <-- it's a text type and it suites the `group`
  .where({ userId });
```

`group` has no problems at grouping by plain values, and on TS level it's allowed, while grouping by json values is intentionally disallowed on TS level because postgres won't let you do that.

#### reverse the query

In general, when I deal with `group` I'm thinking if and how can I reverse the query to avoid grouping. Because the query becomes simpler for the reader, and I suspect it's also more efficient for the database. Maybe in this case it's not more efficient, cannot promise that.

```ts
  const result = await db.location
    .select("id", "name", {
      // region: (q) => q.region,
      checkInCount: (q) => q.checkIns.where({ userId }).count(),
    })
    .where({ checkInCount: { not: 0 } });
```

Here we can select any data from the location, and select count of checkins for a specific user, and in the end filter out 0 values.

For this I added checkIns relations to the location:

```ts
checkIns: this.hasMany(() => UserCheckInTable, {
  columns: ["id"],
  references: ["locationId"],
}),
```

The region in the query above is commented out, because I found a TS bug, once it is uncommented TS starts complaining, though the query still works as expected. I'll fix.

#### a more complicated one, using `$from`

```ts
const result = await db
  .$from(
    db.userCheckIn
      .select("locationId", {
        checkInCount: (q) => q.count(),
      })
      .group("locationId")
      .where({ userId }),
  )
  .select("locationId", "checkInCount", {
    locationRegion: () =>
      db.region.whereExists(
        "location",
        (q) => q.whereSql`${q.ref("id")} = "locationId"`,
      ),
  });
```

Here is an inner query selecting only `locationId` and `checkInCount`, not selecting region so no need to group by it.
And then the outer query additionally loads the region info. A bit of raw sql was needed to connect ids.

Maybe this is more efficient, maybe not. Apparently, looks more complicated.

**Comment by romeerez** [comment]
Published a fix for 2 cases described above:

1. This query had a type error, now this should be fine:

```ts
  const result = await db.location
    .select("id", "name", {
      region: (q) => q.region,
      checkInCount: (q) => q.checkIns.where({ userId }).count(),
    })
    .where({ checkInCount: { not: 0 } });
```

2. When using $from, fixed `ref` helper to be able to reference a column of the outer query:

```ts
const result = await db
  .$from(
    db.userCheckIn
      .select("locationId", {
        checkInCount: (q) => q.count(),
      })
      .group("locationId")
      .where({ userId }),
  )
  .select("locationId", "checkInCount", {
    locationRegion: (outer) =>
      db.region.whereExists(
        "location",
        (inner) => inner.where({ id: outer.ref('locationId') }),
      ),
  });
```

**Comment by matthewmorek** [comment]
Thanks for a detailed response, and apologies for not being able to respond to this earlier. After what you've showcased above, it makes sense to me to rewrite my query to use a direct relation of `userCheckIn` with `location`, I definitely overlooked that part!

I'll attempt implementation in the coming days and report back, but I'm sure this will solve many other problems that might be coming up with these types of queries in Orchid.
