### ISSUE TITLE
Error during generation if project contains 10 or more checks

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#435]
I was having a real headscratcher recently, trying to generate migrations but it kept erroring out

```js
[redacted]\node_modules\pg\lib\client.js:535
          Error.captureStackTrace(err)
                ^

error: relation "orchidtmpview2" does not exist
    at [redacted]\node_modules\pg\lib\client.js:535:17
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async performQuery$1 ([redacted]\node_modules\pqb\src\adapter.ts:188:12)
    at async <anonymous> ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\generators.utils.ts:53:9)
    at async Promise.all (index 1)
    at async compareSqlExpressions ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\generators.utils.ts:25:5)
    at async Promise.all (index 1)
    at async processTables ([redacted]\node_modules\orchid-orm\src\migrations\generate\generators\tables.generator.ts:133:52)
    at async composeMigration ([redacted]\node_modules\orchid-orm\src\migrations\generate\composeMigration.ts:54:5)
    at async adapter.transaction.text ([redacted]\node_modules\orchid-orm\src\migrations\generate\verifyMigration.ts:50:12) {
  length: 112,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'namespace.c',
  line: '434',
  routine: 'RangeVarGetRelidExtended'
}
```

After hours of reverse engineering it all pointed to this line of code
https://github.com/romeerez/orchid-orm/blob/db189d5eeafbf3381c61628abd1a02f10ee30ac4/packages/orm/src/migrations/generate/generators/generators.utils.ts#L52

It seems that the query fails because the temporary view doesn't exist, even though it is literally created just a few lines before it. I tried debugging this but all signs pointed that the view is clearly created, but the query still kept failing.

I then tried removing `TEMPORARY` from the query here:
https://github.com/romeerez/orchid-orm/blob/db189d5eeafbf3381c61628abd1a02f10ee30ac4/packages/orm/src/migrations/generate/generators/generators.utils.ts#L30
 and voila, it now works. The view is then properly dropped leaving no trace in the db.

I have no idea when this happens, and why a temporary view fails here (concurrency?, I don't use a connection pool FWIW).

**Comment by romeerez** [comment]
This code runs every time when you run the generator and if you have raw sql expressions anywhere in the tables definitions. This may be executed for the checks, or for sql defaults, and there are other cases.

This is strange if that worked for you before, as you used checks before, and now suddenly it stopped.

> I have no idea when this happens

Cool, and how am I supposed to debug it? :)
Works on my machine.

> The view is then properly dropped leaving no trace in the db.

Yes it's dropped, but what if the process suddenly fails, what if you stop it with ctrl+c at the moment before dropping? Then the view is persisted, and the next generation will fail, and this would cause questions, debugging, and dropping the views manually, so having it as `TEMPORARY` is better. I'd like to figure out the root cause of the issue.

Could you provide more info? Ideally, if you can make a reproduction.

What is the postgresql version? Just in case, can't it be that you were using a different postgres version recently and it worked, but then switched to older version?

**Comment by mordechaim** [comment]
Hah lol, I couldn't create a reproduction in isolation. 

It happens when I add one more check. Simply not adding that check and everything works properly.

I'll try to dig deeper and see if I can create a reproduction.

**Comment by mordechaim** [comment]
Btw through the reverse engineering I realized what you're doing there. It's a genius solution to normalize the raw SQL so you can compare changes

**Comment by mordechaim** [comment]
I was able to reproduce it in isolation!
It happens if I have 10 or more checks in the project.

I went overboard here, but really 10 checks is enough:

```ts
import { BaseTable } from '../baseTable';

export class ATable extends BaseTable {
  readonly table = 'a';

  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    a: t.integer().check(t.sql`a is not null`),
    b: t.integer().check(t.sql`b is not null`),
    c: t.integer().check(t.sql`c is not null`),
    d: t.integer().check(t.sql`d is not null`),
    e: t.integer().check(t.sql`e is not null`),
    f: t.integer().check(t.sql`f is not null`),
    g: t.integer().check(t.sql`g is not null`),
    h: t.integer().check(t.sql`h is not null`),
    i: t.integer().check(t.sql`i is not null`),
    j: t.integer().check(t.sql`j is not null`),
    k: t.integer().check(t.sql`k is not null`),
    l: t.integer().check(t.sql`l is not null`),
    m: t.integer().check(t.sql`m is not null`),
    n: t.integer().check(t.sql`n is not null`),
    o: t.integer().check(t.sql`o is not null`),
    p: t.integer().check(t.sql`p is not null`),
    q: t.integer().check(t.sql`q is not null`),
    r: t.integer().check(t.sql`r is not null`),
    s: t.integer().check(t.sql`s is not null`),
    t: t.integer().check(t.sql`t is not null`),
    u: t.integer().check(t.sql`u is not null`),
    v: t.integer().check(t.sql`v is not null`),
    w: t.integer().check(t.sql`w is not null`),
    x: t.integer().check(t.sql`x is not null`),
    y: t.integer().check(t.sql`y is not null`),
    z: t.integer().check(t.sql`z is not null`),
  }));
}
```

**Comment by romeerez** [comment]
Thank you for investing your time into research!

Regarding the approach, yeah, that was a very nice trick to discover, I remember spending quite a lot of time searching for a solution, but there is literally no adequate working way to compare SQLs, I tried everything I could find on the internet and brute-forced native postgres functions to find the one that could finally do that.

The bug is about concurrency, it won't be difficult to fix, I'll do it on Sat.
In the meantime, you can add `max: 2` option to your db config in `rakeDb`:

```ts
export const change = rakeDb(
  {
    databaseURL: process.env.DATABASE_URL,
    max: 2, // <--
  },
  {
    // ...
  },
);
```

1 is not enough for some reason, and 2 solves the concurrency problem.

Finding the root cause is the most difficult part, thank you for that!

**Comment by mordechaim** [comment]
Setting `max: 2` or any larger number doesn't seem to have any effect on this issue for me.

**Comment by romeerez** [comment]
I published a fix for the concurrency problems.
