### ISSUE TITLE
Camel-cased table names in where condition not accepted

### ISSUE THREAD

**Issue by lithdew** [romeerez/orchid-orm#44]
With a database where table names and column names are snake-cased, and `snakeCase: true`, in `.where` conditions, table names seem to only be accepted should they be specified as snake-cased whereas column names may be either camel-cased or snake-cased.

The following code throws `error: missing FROM-clause entry for table "commentsOnPosts"`:

```ts
.select({
    numPosts: q => db.posts.count().whereNotExists(db.commentsOnPosts, "commentsOnPosts.commentId", "posts.id").where(q.raw("posts.author_id = accounts.id")),
})
```

The following code however works:

```ts
.select({
    numPosts: q => db.posts.count().whereNotExists(db.commentsOnPosts, "comments_on_posts.commentId", "posts.id").where(q.raw("posts.author_id = accounts.id")),
})
```

**Comment by romeerez** [comment]
Aha, it's not a bug, because camel-to-snake transformation is only meant for column names, not for tables.

I assume that you never or almost never have to use table names in the queries, so the lib can relax on this and not perform additional mappings.

The table name is set as it is in the db.

I'll empathize with this in the docs for the snake case option.

In addition to omitting the table name, or using object { commented: 'id' }, you can also alias the table and use the alias:

```ts
.whereNotExists(db.commentsOnPosts.as('c'), "c.commentId", "posts.id")
```

But still, there is a bug, that you received `missing FROM-clause entry` when it must be a TS error saying that "commentsOnPosts.commentId" is not acceptable here.

**Comment by romeerez** [comment]
Fixed: now `whereExists` and all similar `Exists` and join methods will highlight if something is wrong with a string argument.
