### ISSUE TITLE
Composite primary key array is broken

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#57]
I could fix this by just adding multiple primary keys individually, but it seems like `...t.primaryKey(['keyOne', 'keyTwo'])` composite primaryKey is now broken as of one of the recent updates.

**Comment by romeerez** [comment]
Please let me know how and where is it broken. Broken in migration or in the table classes? TypeScript error or runtime error?

**Comment by quinnvaughn** [comment]
On migration it was telling me the primaryKey didn't exist for the table (which was a composite like that). This is code that I haven't updated outside of updating the rake-db and orchid-orm versions.

Seems like I'm also having another issue with migrations about a foreignKey relation saying it doesn't exist when trying to add my seed data, which once again worked fine on previous versions. 
```
 INSERT INTO "user"("displayName", "username", "email", "password", "roleId", "id") VALUES ($1, $2, $3, $4, $5, $6), ($7, $8, $9, $10, $11, $12) RETURNING * ['John Doe', 'johndoe', 'johndoe@gmail.com', '$2b$10$53a0zsw2z/qj9GWyB3AvceNgtrn3vfjV3zR7RPNuzT199EQJNVoT6', 'wmqvk83h9kw94ja1i7ytxtjn', 'i5jhcbllv7d2usrc3e4mnean', 'Jane Doe', 'janedoe', 'janedoe@gmail.com', '$2b$10$dnaSLOmO/KjGPaN0/IGTT.VRknKFInPz2G2VtXcNgFwwTzsK/7Ezq', 'j2n1gpjnchpafb6n1fjpka9d', 'uvlcfsix27ep79ar8ocoka5v'] Error: column "roleId" of relation "user" does not exist
```

It then shows the db instance which does seem to be aware of roleId so I'm not sure what the issue is.

**Comment by quinnvaughn** [comment]
Ok so re the second issue it's literally any single instance of adding a foreignKey if I'm also not creating the tables in the same migration.

```
await db.createTable('location', (t) => ({
    id: t.text().primaryKey(),
    name: t.text(),
    url: t.text().nullable(),
    updatedAt: t.timestamps().updatedAt,
    createdAt: t.timestamps().createdAt.index().default(t.raw('now()')),
    addressId: t.text().foreignKey('address', 'id').index(),
  }))

  await db.changeTable('dateStop', (t) => ({
    locationId: t.add(t.text().foreignKey('location', 'id').index()),
  }))
```

So this wouldn't work, but adding location before the createTable call with 'dateStop' would work.

**Comment by quinnvaughn** [comment]
So I updated all my migrations to account for that, which is obviously super brittle, but it is a temporary fix. I'm not sure *why* it's not working like that, but it isn't.

**Comment by romeerez** [comment]
I'm confused, so there are two issues here: one for primary key and second for foreign key.

I need your guidance in order to reproduce it to fix it.

For the primary key:

> On migration it was telling me the primaryKey didn't exist for the table

Could you share the code that is not working? I assume the following is not working, right?

```ts
await db.createTable('tableName', (t) => ({
    ...t.primaryKey(['one', 'two']),
}))
```

> another issue with migrations about a foreignKey relation

The error tells "roleId of user doesn't exist", it's an SQL error that we can trust, it guarantees that the column indeed doesn't exist. I need to know more context to know why you expect it to exist and where is the potential bug.

> So this wouldn't work, but adding location before the createTable call with 'dateStop' would work.

It's hard for me to follow. "adding location" - location is a table that you're creating, "before the createTable call with 'dateStop'" - in your code it is `changeTable('dateStop')` and not create.

Ideally, if you could push your code to a repo so I could check it that would help a lot.

**Comment by quinnvaughn** [comment]
Not going to push to a repo, this is relatively proprietary code, so I'll just share what I can.

Issue 1.
Yes that is correct. 
I had to change it to 
```
t.field('one').primaryKey()
t.field('two').primaryKey()
```

to get it to work. the array did not work.

Issue 2.
I had the user table already, then in a different migration I created the role table that has a reference to the user table, so I added a foreignkey to role in the same migration. This code previously worked in previous rake-db versions. 
What I had to do in the meantime was add role to the same migration as the user, and then just added roleId as a normal field, not a `t.add(...)` field. I had to do this for several other foreignKeys in the same situation. I'm not sure if it's that the `t.add()` doesn't work with foreignKeys anymore and you have to use `t.addForeignKey()` and that solves the problem. If so it would just be another breaking changes situation.

**Comment by romeerez** [comment]
Alright, got it, so:

1) composite primary key is not working in migrations
2) `t.add(...)` is expected to add a new column and a foreign key in one turn, but it doesn't work

**Comment by quinnvaughn** [comment]
Correct

**Comment by romeerez** [comment]
Just tried the composite primary key and it works for me:

```ts
import { change } from '../dbScript';

change(async (db) => {
  await db.createTable('tmp', (t) => ({
    one: t.text(),
    two: t.text(),
    ...t.primaryKey(['one', 'two']),
  }));
});
```

Logs show the following SQL:

```sql
CREATE TABLE "tmp" (
  "one" text NOT NULL,
  "two" text NOT NULL,
  PRIMARY KEY ("one", "two")
)
```

**Comment by romeerez** [comment]
Cannot reproduce the second problem as well:

```ts
import { change } from '../dbScript';

change(async (db) => {
  // create table dateStop without locationId
  await db.createTable('dateStop', (t) => ({
    id: t.text().primaryKey(),
  }));

  // create location table
  await db.createTable('location', (t) => ({
    id: t.text().primaryKey(),
  }));

  // add locationId column with a foreignKey to location id
  await db.changeTable('dateStop', (t) => ({
    locationId: t.add(t.text().foreignKey('location', 'id').index()),
  }));
});
```

@quinnvaughn what should I change?

**Comment by quinnvaughn** [comment]
So my situation for number two was that the dateStop was originally created in a different file, then location and locationId in the same file. So I would check that that still works and then I will see what's up with mine.

**Comment by romeerez** [comment]
It doesn't matter for rake-db if the table was created in the same file or a previous one, it always executes from the oldest file to the newer file from top to bottom when migrating.

But there is one important thing about `rollback`:

```ts
import { change } from '../dbScript';

change(async (db) => {
  await db.createTable('name', (t) => ({
    // ...
  }));

  await db.changeTable('name', (t) => ({
    // ...
  }));
});
```

The code above first creates a table and then modifies this table, it's okay when migrating, but it will fail when doing `rollback` because it will first drop the table and then will try to revert the change.

When you have a `createTable` and `changeTable` for the same table in the same file, or if you're creating a table and then referencing it with a foreign key in the other table, you should separate these steps into multiple `change` blocks:

```ts
import { change } from '../dbScript';

change(async (db) => {
  await db.createTable('location', (t) => ({
    // define columns
  }));
});

change(async (db) => {
  await db.changeTable('dateStop', (t) => ({
    // add foreign key
  }));
});
```

Having multiple `change` in a single file is ok. With this code, rollback of this file will: 1) remove the foreign key 2) drop the location table.

I guess you were doing rollbacks and something went wrong with tables, and that's why the problems appeared.
