### ISSUE TITLE
[docs] add jsdocs for public apis/interfaces

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#64]
I did see this plan in `Github Project` a few days ago.
When I started to integrate orcild into my project, I found it important to have a well explained docs.

Could you please add some examples on how to add jsdocs, I can help to add others

**Comment by romeerez** [comment]
Github Project makes sense when many people are working on it but in my case, I just use a local todo text file and didn't update the plan on GitHub, and the plan on GitHub was running out-of-sync and out-of-date. So I removed it.

JSDocs (or TSDocs) I guess will reflect the documentation, so almost the same info that is on the website will be in code comments. 

Example how [kysely](https://github.com/kysely-org/kysely/blob/master/src/query-builder/insert-query-builder.ts) does it: they write text, have links in it, and add code examples.

I'm not writing these comment docs because it would be tiresome, and I have many other more interesting plans for improving the ORM, but surely such docs are useful and helpful for users, and sooner or later they should be added.

**Comment by bingtsingw** [comment]
I agree that `comment docs` can be tiresome, especially when syncing it with the code and documentation, I seldom write it in my own project, too.

But it do save time when I want to explore the api usage. Looking through the documentation is OK, but not as quick as `cmd + click`.

Anyway, if you need any help, I can write these kind of docs.

**Comment by romeerez** [comment]
Of course, I'll be very grateful for your help!

If you really like the ORM and going to use it in the future, you could learn it deeper by reading the website and writing corresponding docs in the code. And later you will be more familiar with the code and could make a feature or a bug fix. I'll be happy to have a collaborator.

Make sure your editor can do grammar checks.

**Comment by bingtsingw** [comment]
Yes, I quite like this ORM, I have used lots of ORMs , and `orchid` is the one I'm waiting for years in `nodejs` ecosystem.
I'm integrating it into my project and refactoring my old queries, seems to work nicely.

There is no need to feel awkward because it's a natural for me to learn and dive deep into the library by contributing docs or fixing bugs.

By the way, I'm glad to see this project to be more mature and recognized by more people
