### ISSUE TITLE
[docs] more docs for `modifyQuery`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#71]
`modifyQuery` is a powerful tool to extend the query builder, but it's [doc](https://orchid-orm.netlify.app/guide/common-column-methods.html#modifyquery) is too simple.

This is my use case, I want to make my `updatedAt` update at `UTC`, after I dig into the source code, I finally worked out some code like this:
```
updatedAt: () =>
  t
    .timestampNoTZ()
    .default(() => new Date().toISOString())
    .modifyQuery((table) => {
      (table.query as any).updateData = [
        { __raw: '"updated_at" = now() AT TIME ZONE \'UTC\'', __values: undefined },
      ];
    }),
```

It could be easier if there are more docs.

**Comment by romeerez** [comment]
I don't want to expose the inner details of the ORM because it's tricky to work with, and inner details can change in new releases since I don't expect people to rely on them.

Can't you use `...t.timestampsNoTZ()` instead?

Or if you have only `updatedAt` column, can't you use the following instead?

```ts
updatedAt: t.timestampsNoTZ().updatedAt,
```

**Comment by bingtsingw** [comment]
`timestampsNoTZ` modifies the query to update `updatedAt` to "now()" which is not `UTC`, so I hacked it this way to always save datetime to database in `UTC` format.

**Comment by bingtsingw** [comment]
I thought `modifyQuery` is a public api to extend the query builder, but if it belongs to the inner details of the ORM, I think there should be another simpler api to extend the query builder for advanced operation such as [soft delete](https://github.com/lookinlab/adonis-lucid-soft-deletes), [sortable](https://github.com/spatie/eloquent-sortable) and so on

**Comment by romeerez** [comment]
I played a bit with it and reproduced the problem:

```sql
CREATE TABLE tmp (
  timestamp timestamp,
  timestamptz timestamptz
);

-- by default, now() is in UTC:
SELECT now();
-- I have 2023-05-04 14:58:23.701884 +00:00

INSERT INTO tmp VALUES (now(), now());

-- change timezone to something else:
SET timezone TO +5;

SELECT now();
-- now the value is 2023-05-04 19:59:30.674339 +05:00
-- this is exactly the same time, but in different time zone

INSERT INTO tmp VALUES (now(), now());

SELECT * FROM tmp;
-- timestamp                   timestamptz
-- 2023-05-04 15:03:09.136372, 2023-05-04 20:03:09.136372 +05:00
-- 2023-05-04 20:03:20.009841, 2023-05-04 20:03:20.009841 +05:00
```

So that's why `timestamptz` is a recommended type - no matter what the current time zone is, it saves time correctly.

I remember you can't migrate to `timestamptz`, but maybe you can change the timezone of db to UTC? That would also solve the problem. AFAIK, UTC is the default time zone disregarding your location.

How I can improve ORM for handling your case: it could accept a config parameter like the following:

```ts
export const BaseTable = createBaseTable({
  now: `now() AT TIME ZONE 'UTC'`,
});
```

And use this user-provided SQL in every place where it is using `now()`.

I was going to add Soft delete functionality later, and for the Sortable you gave - I'll check what it is and perhaps also include it in plans. Implementing it on the user side is tricky and error-prone, it should be handled by the ORM.

Looks like `modifyQuery` indeed relies too much on inner details and better to remove it from the docs.

**Comment by bingtsingw** [comment]
Thank you for your patient reply.

## timezone
I'll dive deeper into postgres `timezone` sometime to see if I can migrate to `timestamptz` or change my database to `UTC`, as it's an old running database, this process may take long to be done. Until then, I'll go with hack or config parameter if it's implemented.

## extending
Maintaing extra functionalities in the main repo is of course possible, but I have some concerns:

- End-user may have lots of non-standard scenarios and requirements which is not suitable to add into the main repo, anyway we need some mechanism to extend the ORM.
- Even if we'll implement some of the functionalities into the ORM, maybe it's better to decouple them as separate packages, such as `orchid-plugin-solf-delete`, `orchild-plugin-sortable`, `orchid-plugin-plugable`, `orchid-plugin-searchable` and so on.

So I suggest we carefully expose a set of limited api to replace the complex `modifyQuery`, official and third party packages should relay on these apis to extend the ORM.
I find there are [callbacks](https://orchid-orm.netlify.app/guide/callbacks.html) which are close to, but they work on `table.query`, not on `createTable`.

**Comment by romeerez** [comment]
Sure, but it's not an option to reveal internals, because each new release of Orchid ORM would have a risk to break third-party plugins. Plugins should rely on a public interface, and if you want to build a plugin and there's something missing in the ORM for it - let me know, open an issue, and let's extend the ORM the way it is flexible enough for the plugin.

> we carefully expose a set of limited api to replace the complex `modifyQuery`

Of course, this API depends on the specific case, in your case with `updatedAt` I think that customizing `now()` is what's needed.

**Comment by bingtsingw** [comment]
Yes, customizing `now()` is enough for `updatedAt` case, and I mentioned a public interface just for future functions.

**Comment by romeerez** [comment]
I published update for this, hope this works for you, let me know: [nowSQL option](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#nowsql-option)

**Comment by romeerez** [comment]
Assuming this works for you, let me know if something
