### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#77]
Is there any interest in adding full text search in the future?

**Comment by romeerez** [comment]
Of course, it's a must-have feature. I hope you don't need it right now because I'm planning to do other things in the near weeks. It doesn't seem to be a large feature, maybe I could do it earlier.

**Comment by romeerez** [comment]
I'm planning to add a `search` key in Prisma for a basic use-case, but more importantly to change the existing `raw` method that takes SQL string and then variables, into `sql` method that accepts a template literal, and to make `where` and other methods to be able to accept SQL:

```ts
const query = 'some & search';

db.article.where`
  to_tsvector(title || ' ' || body) @@ to_tsquery(${query})
`
```

It should simplify using various postgres functions and building custom queries.

**Comment by akutruff** [comment]
I could make another GH issue about this if you like, but expanding on this point 

From the docs:

> Support for JOIN LATERAL is in the plans, it will enable an interesting optimization of joining and selecting relations.
> 
> Cannot select record with relations in the create, update, and delete queries.
> 
> No helpful methods available for PostGis, full text search, trigram search. Need to use raw SQL pieces for this.
> 
> Range database types, composite custom types aren't supported.
> 
> There are some methods for searching in JSON columns, but just very basic, need more.
> 

This is unfortunately why I'm going to continue to use slonik, and the reason why I have been bitten by ORMs,  especially Prisma.  Prisma treats things like composite keys, PostGIS, and custom types as a "nice to have" rather than a core requirement.  Composite keys, PostGIS, etc. are **core** things that real world apps need.  Really, if you look at any ORM, it's where they become worthless and a regretted choice as you need to hack together custom queries and then the ORM itself becomes a burden.  

My previous comment on this issue:
https://github.com/romeerez/orchid-orm/issues/12#issuecomment-1505870570

I encourage you to really make sure that the overall design of the library accounts for these scenarios early in the project and bump up the priority.  Users should always be able to expand the library themselves with custom types and raw SQL BUT also be able to fold it into the higher level parts of the ORM.  

Anyway, thanks for letting me pound on this issue.  I really really want to use Orchid, but can't pull the trigger until I know that all the work I put into utilizing Postgres is available to me.

**Comment by romeerez** [comment]
Neither I nor the big teams behind other ORMs are physically able to cover everything. That's a turn-off in the case of Prisma, as it's simply impossible to build specific queries with it, rather than writing them completely as a raw SQL. But it's not such a big deal with Orchid ORM and some other ORMs that allow using ORM models/interfaces and injecting only some pieces of raw SQL where needed.

Composite keys are indeed something that is currently lacking if we are talking about a situation where one table is referencing the other table by multiple columns. This is important and I'll try to add support for this in the near future.

> I encourage you to really make sure that the overall design of the library accounts for these scenarios

That was an idea from the beginning: adding gradually various helpers to simplify common cases, and allow to inject only a piece of raw SQL where needed.

 > Users should always be able to expand the library themselves with custom types and raw SQL

Actually, that is in there: column types are customizable, and you can add your own type, and set a custom function to encode and decode it.

> until I know that all the work I put into utilizing Postgres is available to me.

That's the goal, it will take more time. Right now, it's not a secret, some features aren't implemented, and different functionalities even weren't taken into account, like table inheritance for instance, there are tons of features that Postgres has.

> but more importantly to change the existing raw method that takes SQL string and then variables, into sql method

The `sql` method I mentioned in the message above is implemented and published.
It is similar to what `slonik` does.

**Comment by romeerez** [comment]
I looked closer into Postgres FTS capabilities, and it's so overwhelming. The good news: other ORMs don't even try to support this decently, the Orchid ORM could be the first.
But, it will take a lot of time and effort.

**Comment by romeerez** [comment]
Ready! [Here are the docs](https://orchid-orm.netlify.app/guide/text-search.html).
