### ISSUE TITLE
[bug] `nowSql` seems to not work with `.create`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#78]
I have `nowSql` configured, when I `.update(dto)`, it works as expected.
But when I `.create(dto)`, it seems to have no effect, `createAt` and `updateAt` all have the value `now()`

**Comment by romeerez** [comment]
> But when I .create(dto), it seems to have no effect,

I apologize if the docs for `nowSQL` wasn't clear enough, it's designed so: it has no effect when creating a record, but it has an effect in the migration so that the timestamp column will have a custom default SQL, so you need to make and run a migration for it.

It's done so because it's more efficient to have defaults in the database rather than sending more values each time when creating a record.

I updated [nowSQL](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#nowsql-option) docs with more details.

I found a minor bug around this and already realized a fix: `now() AT TIME ZONE 'UTC'` will now be wrapped into `()` because it previously failed when running the migration.

**Comment by bingtsingw** [comment]
Thank you for your explanation, I found that docs for [`t.default()`](https://orchid-orm.netlify.app/guide/common-column-methods.html#default) do explain this design :)
