### ISSUE TITLE
raw sql to support name placeholders

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#85]
## Problem

I would like to write raw sql that refers to column names that are only known in runtime:

```ts
const { column, value } = await getColumnAndValue()
db.table.raw('$column = $value', { column, value })
```

with objection/knex, that is possible with `?? = ?`. I don't see how it's possible with pqb.

## Suggestions

Perhaps a special syntax like `$$column`?

**Comment by IlyaSemenov** [comment]
So what if column happens to be `"; DROP DATABASE users; --` ?

**Comment by IlyaSemenov** [comment]
Some background: I'm porting https://github.com/IlyaSemenov/objection-graphql-resolver to orchid-orm. That's why I need some edge cases which are not normally needed in userland...runtime column names (coming from graphql inner data) in particular.

**Comment by romeerez** [comment]
That's awesome that you've chosen Orchid as a replacement for the Objection and building an open-source project for it!
We could chat about things in Discord if you're willing.

**Comment by romeerez** [comment]
Changed `raw` method:
- renamed to `sql` - seems to be a better name
- changed the way it works:
  instead of
  ```ts
    raw('$$column = $value', { column: 'column', value: 'value' })
  ```
  not this is
  ```ts
    sql({ raw: '$$column = $value', values: { column: 'column', value: 'value' } })
  ```
  it's more to write, but `raw` here is needed to remind the devs that this is a raw SQL, interpolation here is dangerous
- and now it supports template literal, yay!
  ```ts
    sql`column = ${123}`
  ```
  it will collect and pass values in a safe way.
  Passing a column name with `$$` is still possible, though looks awkward:
  ```ts
    sql({ column: 'column' })`$$column = ${123}`
  ```
- `raw` method is preserved so it's not a breaking change, added a deprecated flag to it.

**Comment by IlyaSemenov** [comment]
@romeerez

```ts
db.user.sql({ column: 'column' })`$$column = ${123}`
```

this gives TS error in orchid-orm@1.9.42, pqb@0.11.34

<img width="829" alt="image" src="https://github.com/romeerez/orchid-orm/assets/128121/a88578b8-5c41-4809-9563-e2c4dd64d3e5">

Has it been changed since then?

**Comment by romeerez** [comment]
Yes, it's { values: { column: 'column' } } (note the values)
