### ISSUE TITLE
addParserToQuery silently overwrites existing parser

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#92]
The name of `addParserToQuery` suggests that the parser will be added...instead, it silently overwrites the existing parser. Consider the use case:

```ts
const users_q = db.user.select("id")
addParserToQuery(users_q.query, "id", (id) => `a:${id}`)
addParserToQuery(users_q.query, "id", (id) => `b:${id}`)
console.log(await users_q.get("id"))
```

This prints `b:1` rather than `b:a:1`.

#### Suggestions (more to less desireable):
* stack parsers
* throw exception to prevent accidental overwrite
* rename as `setQueryFieldParser` or something else that better tells that it's not adding but setting/replacing

**Comment by romeerez** [comment]
Renamed `addParserToQuery` to `setParserToQuery`, and added additional `overrideParserInQuery`.

Moved them from `pqb` to `orchid-core`, and added code docs.

In the `overrideParserInQuery` first added parser will be executed first, and the second parser will get the output from the first one.

**Comment by romeerez** [comment]
Imagine we have a table A with column `col`, and it has some parser. That's set when [defining a table](https://orchid-orm.netlify.app/guide/common-column-methods.html#parse), and all the query objects for this table will have this parser by default.

But then, we're joining a table B which also has a column `col`, it has a different parser, and we've selected the `B.col`. And it was intended that the parser will be overwritten, because mixing two different parsers may lead to problems.

Or instead of joining a table, we can select a raw SQL value and define a column type for it, and when defining the column type we can set the parser right here, and it will also conflict with the original one.

So, replacing parsers should be ok, but stacking them may result in bugs, depending on what are you using it for.
