### ISSUE TITLE
[bug] `.parse` not work for `null` value

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#96]
```ts
export class TestTable extends BaseTable {
  columns = this.setColumns((t) => ({
    test: t.varchar().nullable().parse((input) => input ?? 'default when input is null')
  })
```

The parse is called if `test` has value, but not called when `test` is null

**Comment by romeerez** [comment]
This makes `parse` simpler for users, to not think about the `null` case.

If the column should have a default, it's a database-level default set in the migration, or it can be app-level default that's generated before creating a new record.

Why have a nullable column, but set a default value when loading a record, and not before saving, what is the use-case for it?

**Comment by bingtsingw** [comment]
There are many cases that I want to handle the default value in app-level on fly.

I have an article `banner` field which is default to null, and I want to show a default banner if it's not set by user.

**Why not generated before creating :**
First I only want to save user uploaded value to database, not app specific value.
Second the default banner set by the app maybe changed over time depending on product manager‘s idea. I even encountered a case where I need to get a random value(based on an array of links) on the fly if some field is null.

Anyway, I don't want to lose the flexibility to handle `null` in my app.

**Comment by romeerez** [comment]
Understood, the use case is clear.

I don't want to change `parse` behavior because it may cause some undesired things.

Let it be:
- `parse` is parsing values (NULL is absence of a value, it's not a value) into other values
- `default` is a default when creating
- `defaultOnLoad` - I'll add a new method specifically for the case that you've described. Maybe you could suggest a better name, or does this one looks good?

**Comment by bingtsingw** [comment]
Before discussing the name, I‘d like to know when `parse` and `defaultOnLoad` would be called, for a `null` value, will it call `defaultOnLoad` and `parse` sequentially or `defaultOnLoad` only?
More question, is `null` is exactly `=== null`, what about empty string or something?

These may need to be clarified in the doc.

**Comment by romeerez** [comment]
```ts
// first it will call defaultOnLoad
if (value === null) value = defaultOnLoad?.(value)

// second it will call parse
if (value !== null && parser) value = parser(value)

return value
```

**Comment by romeerez** [comment]
Okay, I think that letting `null` to the `parse` function will be easier to implement, and fewer methods to know about for users.

**Comment by bingtsingw** [comment]
Both are ok for me, I prefer `parse`-for-all solution, just note that this is a breaking change.

**Comment by IlyaSemenov** [comment]
`parse` and `encode` are supposed to work with data _format_. They are supposed to be a bridge between arbitrary Javascript objects (such as `Date`) and javascript types compatible with underlying database types (such as `string` stored in `varchar`). Since `null` values are native for the database, I believe not parsing and not encoding nulls is the right thing to do.

Then, `parse` and `encode` are supposed to generate consistent result to each other's output.

The default banner use case mentioned here is related to data _content_ rather than its format. While a valid scenario per se, I think using `parse` for it is kind of misuse. Not only because of the nulls, but also because that breaks implied coupling with `encode`.

What I would suggest is adding `.transform` on field level. Technically that will be a more or less duplication of `.parse` (chained _after_ the actual `.parse`), but mentally it introduces a different thing. The naming clearly distinguishes that the data will be transformed to arbitrary shape, possibly irrevocably so. It's reasonable for it to accept all data (including nulls). There is no mental coupling with `encode` whatsoever. As a new method, adding it is backwards compatible.

**Comment by romeerez** [comment]
I like the `.transform` idea, need to think about it.

**Comment by romeerez** [comment]
I already implemented the change for `parse` (locally, not published), and also it seems fine.

```ts
// arg is of string type, no null check is ok
t.date().parse((arg) => new Date(arg))

// arg is of string | null type for a nullable
t.date().nullable().parse((arg) => arg ? new Date(arg) : null)

// when returning a default value instead of null,
// it will also affect the result type
t.date().nullable().parse((arg) => arg ? new Date(arg) : new Date()) // current time is a default

const data = db.myTable.select('dateColumn')
data.dateColumn // is of type Date because it defaulted
```

It was quite a simple change, and it was simple for users.

What do you think, @IlyaSemenov?

I agree that "parsing a null into a default value" sounds wrong, but, it depends on how we think about it. I could also say "parsing the value returning to a db to another value", and the value can be null, the returning may be a hardcoded string, but that's not a big deal.

**Comment by bingtsingw** [comment]
This sounds reasonable, `transform` is a good name. And as the name suggest, we may move `.transform` to be called after `parse`.

But adding too much method is also complicated, especially in types.
```
function parse(value: NonNullable<ColumnType>) ;

function transform(value: ColumnType | ReturnType<typeof parse>)
```

Another thing to note, if I can handle everything(format as well as content) in `transform`, `parse` seems less useful.

**Comment by romeerez** [comment]
Okay, I'm going to do the following:

- `parse` remains as it was, internally this function is wrapped to prevent nulls from getting here:
```ts
// internally
parse(fn) {
  this.parser = (val) => val === null ? null : fn(val)
}
```

- and I'm adding the `transform` which will act as shown in my message above

**Comment by IlyaSemenov** [comment]
To be honest as I thought more I started to think that handling nulls in parse/encode should be allowed. There are multiple scenarios when use may want to store or avoid storing nulls even if allowed by the database (such as asserting uniqueness in Postgres<15 where there is no `nulls distinct`, simplifying ordering without having to deal with `nulls first` etc.) Also, allowing `parse` to return some kind of 'default singleton object' or special kind of `NaN` (e.g. when storing fractional numbers) is also reasonable.

Now then if user wants to abuse `parse` to return a default banner, so be it. :)

**Comment by romeerez** [comment]
Published: now `parse` can handle `null` if the column is nullable, [here are the docs](https://orchid-orm.netlify.app/guide/common-column-methods.html#parse).

**Comment by romeerez** [comment]
@bingtsingw note that from orchid-orm v1.36.0 you should update `parse(x => x === null ? aDefault : x)` to `parseNull(() => aDefault)`, here are [docs](https://orchid-orm.netlify.app/guide/common-column-methods.html#parsenull).

**Comment by bingtsingw** [comment]
@romeerez Thanks for your reminder
